### ISSUE TITLE
github sign in and auto-update of workflow on commit

### ISSUE THREAD

**Issue by bioworkflows** [bioworkflows/bioworkflows-help#1]
It would be great for bioworkflows.com to work well with github. There are several issues

1. Users are unlikely to "sell" workflow if these are open on github, but bioworkflows.com should be able to pull from private repositories.

2. Versioning. We right now use a different ID for different workflow, but it is likely we need a single ID for different versions of the workflow. Keeping track of versions would be a problem.

**Comment by bioworkflows** [comment]
https://github.com/sheppard/django-github-hook

https://github.com/fladi/django-github-webhook

**Comment by BoPeng** [comment]
This has been implemented. Pending further testing, the website will

1. The user needs to sign in with a GitHub account or connect a BioWorkflows account with a GitHub account. (settings -> profile)

2. The workflow needs to have a source url specified with a GitHub url (blob, not raw). The entire repository and/or directory can be specified, and BioWorkflows.com will retrieve `.ipynb` and `.html` files, unless different patterns are specified.

3. BioWorkflows.com will try to create a webhook on the repository. 

4. When a push event happens, all workflows with `source_url` starting from the repository will be updated.
