### ISSUE TITLE
Orders > Add Credit > User has already converted the redeemed card into credit but still system keep shwoing the option of 'convert to credit'

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#102]
![Screenshot (1261)](https://user-images.githubusercontent.com/60692597/191584011-ad1adcd6-c6a6-40d8-8608-04204a079308.png)

**Comment by bioworkflows** [comment]
Please check again because it works well here.

**Comment by Mashhood-Ehsan** [comment]
I have already claimed the gift card, but it still keeps showing me the message of 'unclaimed card'

![15](https://user-images.githubusercontent.com/60692597/191914944-cf5ae1f2-5d65-47fa-83d5-4ee5d7d4a486.PNG)

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![Screenshot (1294)](https://user-images.githubusercontent.com/60692597/192384459-9ce534cb-817a-4903-b255-855572594af3.png)
