### ISSUE TITLE
Community Forum > Post Question > System displays the success message two times, whenever user post a question on platform

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#103]
![Screenshot (1275)](https://user-images.githubusercontent.com/60692597/191907842-f5f2f6f8-c684-4e13-9291-1ded445cfe87.png)

**Comment by bioworkflows** [comment]
Fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![Screenshot (1293)](https://user-images.githubusercontent.com/60692597/192384029-65940104-8e7a-47ad-9e03-15d45d8bf5f5.png)
