### ISSUE TITLE
Upload workflow > Workflow Description > The right and bottom scroll bars should get removed, once user upload a picture. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#108]
This does not look very user-friendly.

![1](https://user-images.githubusercontent.com/60692597/193632829-0648b971-89c5-4a98-b0b6-9af0bc2af8e5.PNG)

**Comment by bioworkflows** [comment]
Changed to `overflow: hidden`. It looked good on another browser.
