### ISSUE TITLE
Forum > Workflow Support > service listings > The ui/ux of 'delivered message' card needs to be improved. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#109]
1. The text is touching the borders.
2. The pixels of the picture are distorted. 
3. The picture is touching the border card. 

![2](https://user-images.githubusercontent.com/60692597/193636869-ada5cf21-489d-44b0-8055-c91752e38786.PNG)

**Comment by Mashhood-Ehsan** [comment]
Plz check the below link, by logging into the "user1"

https://staging.bioworkflows.com/forum/workflow_support_activity/shami5/test-w1.1/shami5-1/user1-1/view/

**Comment by Mashhood-Ehsan** [comment]
Its under request service.

**Comment by bioworkflows** [comment]
I see it now. Thanks.

I believe I have fixed all the problems you listed. Please verify and close so that we can conclude the third round.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed, so closing it.

![Screenshot (1357)](https://user-images.githubusercontent.com/60692597/194933005-643dff9b-d08b-4e92-a325-9c6f3935e772.png)
