### ISSUE TITLE
User logout Operation > when user logged out of the website, system start displaying the multiple random messages/notifications. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#110]
![Screenshot (1312)](https://user-images.githubusercontent.com/60692597/193638947-f4782536-3668-4855-8f5c-43b1ef3080a1.png)

**Comment by bioworkflows** [comment]
The messages are from upstream. They have been suppressed.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it. 

![Screenshot (1352)](https://user-images.githubusercontent.com/60692597/194873761-b8410da4-0c15-4c18-b1f4-f164532773cf.png)
