### ISSUE TITLE
User Profile > Upload picture > when user upload a picture, profile picture becomes eclipse shape.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#111]
The newly uploaded profile picture should remain in the circle format, and not become an eclipse shape.

![3](https://user-images.githubusercontent.com/60692597/193639936-137c0005-b9c1-42e2-b39e-153614a8201b.PNG)

**Comment by bioworkflows** [comment]
The pictures are now properly resized.

**Comment by Mashhood-Ehsan** [comment]
The picture is now in a circle, but its pixels become distorted.

![errrr](https://user-images.githubusercontent.com/60692597/194876269-9e2164ab-6a52-4787-b8a7-e4a87bc9afdc.PNG)

**Comment by BoPeng** [comment]
This looks correct to me. The picture is first cropped from the center and then scaled. For example, I just tried to replace the avatar of user1 with 

<img width="591" alt="image" src="https://user-images.githubusercontent.com/9889312/194883990-c31ede99-6a4d-4c18-bdef-109f6cbe72fb.png">

and the new avatar is

<img width="498" alt="image" src="https://user-images.githubusercontent.com/9889312/194884113-8ab2316c-8b66-47bc-acb6-d03882d70284.png">

**Comment by Mashhood-Ehsan** [comment]
But this does not look very appealing, as you can see pixels are disturbed.

**Comment by BoPeng** [comment]
This is because the original picture has low resolution so the middle portion is actually enlarged.

**Comment by BoPeng** [comment]
The problem was caused by an `ANTIALIAS` method for scaling. It has been fixed.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/9889312/194938902-dea2d821-6496-4aab-ae53-25e9ed7f9c78.png">

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.
