### ISSUE TITLE
Email Subscription > System gave 'Forbidden (403)' error, when user tries to subscribe to an email. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#112]
![4](https://user-images.githubusercontent.com/60692597/193640260-6bb20ed7-a1fd-4636-a1b7-eba36885c3dd.PNG)

**Comment by bioworkflows** [comment]
Were you doing this from the footer? It works fine when I test now.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed, so closing it.
