### ISSUE TITLE
Purchase a plan > pro subscription > User is not able to buy 'pro subscription'. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#113]
When the user clicks on the 'proceed to the checkout button, it gets disabled and stops responding.  

![Screenshot (1313)](https://user-images.githubusercontent.com/60692597/193641160-bd1a6373-6ad8-4feb-9d68-1a7d35cf55a0.png)

**Comment by bioworkflows** [comment]
Fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed, so closing it.

![Screenshot (1354)](https://user-images.githubusercontent.com/60692597/194875734-105a94d0-1068-4e75-84dc-760377443b64.png)
