### ISSUE TITLE
Users > List > Search button is not working, when user click on it, nothing happens. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#114]
![5](https://user-images.githubusercontent.com/60692597/193641951-fddb1b61-38f3-4598-96fc-2d2b7b1ca23e.PNG)

**Comment by bioworkflows** [comment]
Press enter works, clicking the icon does not work.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![Screenshot (1348)](https://user-images.githubusercontent.com/60692597/194774836-2764e0f0-ac50-4b89-9d90-91d222bc068e.png)
