### ISSUE TITLE
User profile > Update bio and banner image > System is not upading the banner image. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#115]
https://share.vidyard.com/watch/UpBoetbTLQEJqVbDKJ4ifC?

**Comment by bioworkflows** [comment]
Cannot reproduce. I have just updated the banner image of user1 without problem.

**Comment by Mashhood-Ehsan** [comment]
Able to upload successfully now, so closing it.

![Screenshot (1355)](https://user-images.githubusercontent.com/60692597/194876970-45f22615-1b51-4763-bc08-96618c903cd2.png)
