### ISSUE TITLE
Admin login > Profile > No option inside the admin dashbaord is working, when user click on any of the option nothing happens.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#118]
https://share.vidyard.com/watch/i68cEpPjw72vQzrpxYz96t?

**Comment by bioworkflows** [comment]
Cannot reproduce... at least after fixing other issues.

**Comment by Mashhood-Ehsan** [comment]
Unable to produce this issue right now, so closing it.
