### ISSUE TITLE
Admin login > Profile > For admin, all the respective tasks are opening at the bottom, they should be opened along side the selected menu option. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#119]
![screencapture-staging-bioworkflows-request-2022-10-03-11_54_32](https://user-images.githubusercontent.com/60692597/193667573-df48ac4e-4d7c-4433-a86d-781e37be4464.png)

**Comment by bioworkflows** [comment]
A missing `</div>`. Fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it

![Screenshot (1347)](https://user-images.githubusercontent.com/60692597/194774697-8d176cb0-5533-4ff7-926f-da914284f44c.png)
