### ISSUE TITLE
Keyword Topic > Select a tag > Alignment is disturbed for the keyword/tag page. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#120]
![7](https://user-images.githubusercontent.com/60692597/193669530-79511404-68a0-4d0b-a10d-578b669fc2be.PNG)

**Comment by BoPeng** [comment]
@Mashhood-Ehsan Could you clarify how do you get to this screen? Is it "Keywords and Expertise" page, or some other workflow page?

**Comment by Mashhood-Ehsan** [comment]
I have tried, but I'm not able to reproduce it right now.
But its related to the 'Keywords and Expertise'

**Comment by BoPeng** [comment]
I think I have found the page. It is related to a topic with a keyword, and the page shows when the keyword is clicked from the tag popover (or maybe some other places that you clicked). I am working on it right now and should push some fix soon.

**Comment by BoPeng** [comment]
This should have been fixed. Go to 'explore expertise', click the 'chat' icon of any tag will show a list of discussion topics with the tag.

**Comment by Mashhood-Ehsan** [comment]
Yes, able to access it now!

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.
