### ISSUE TITLE
Users > List > When user click on the 'developers' option, nothing happens. And system don't display any data.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#122]
![9](https://user-images.githubusercontent.com/60692597/193918612-b84671be-2068-4e33-af4c-9e9d0e9fc490.PNG)

**Comment by bioworkflows** [comment]
Thanks, developers is no longer a separate category.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed, so closing it.

![Screenshot (1346)](https://user-images.githubusercontent.com/60692597/194774637-f2051122-e0a5-4674-b19e-2d408b6377ea.png)
