### ISSUE TITLE
Orders > Purchase > Refund > If a user has already requested for refund, then system mst not display him/her same refund again for same workflow.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#124]
The website can display a message like: "Refund has already been initiated" or "Refund is in progress".

![Screenshot (1320)](https://user-images.githubusercontent.com/60692597/193920624-48673ce1-9e63-4a91-890d-ca8c482ae314.png)

**Comment by BoPeng** [comment]
Disable refund button when a refund is being processed.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed, so closing it.
