### ISSUE TITLE
Workflow > Purchase workflow > System is displaying the dollar sign ($) two times, along with the purchase amount.  

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#125]
![11](https://user-images.githubusercontent.com/60692597/193921423-e59b0aa5-2571-4966-a88c-aab9fe045f00.PNG)

**Comment by bioworkflows** [comment]
Fixed. We changed the backend so that `$` will be added automatically (and other symbols if other currencies are allowed).

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it

![Screenshot (1343)](https://user-images.githubusercontent.com/60692597/194774424-82519cef-08dd-497d-8fb4-e9df84acd612.png)
