### ISSUE TITLE
orders > Transactions > System must display a reasonable/relateable description of transaction, instead of showing 'None' 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#126]
![13](https://user-images.githubusercontent.com/60692597/193922592-65e6597e-bbcd-4143-9ff9-fadeee43961e.PNG)

**Comment by bioworkflows** [comment]
Add description to more items and show invoice if available now.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![Screenshot (1342)](https://user-images.githubusercontent.com/60692597/194774387-a1fd1b6c-44de-4c80-9318-0b9181e14749.png)
