### ISSUE TITLE
Group (organization workflows) or simply collection of group members.

### ISSUE THREAD

**Issue by BoPeng** [bioworkflows/bioworkflows-help#13]
Github allows the creation of organizations that can have its own workflows.  We have two choices

1. Implement `organization` as simply group of users. `bioworkflows.com/org` would simply list all group members and their completed workflows. (Others would only see published workflows).

2. Use the github model where organizations have their own workflows. Then we have an extra layer of complexity and a full github-like "organization" would have its own teams, permissions etc.

**Comment by bioworkflows** [comment]
We will follow the github model, but do not yet have permission for each individual user (yet).
