### ISSUE TITLE
Community Discussion Forum > Unread > There is a time difference between the 'actual post time' and 'Ago Time' for the post. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#137]
![2](https://user-images.githubusercontent.com/60692597/198097844-a22eeafd-c9e3-430f-a675-1d012144c933.PNG)

**Comment by bioworkflows** [comment]
The other time is actually for the last reply, so I added "replied" there.

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/47236991/198189048-84c1581f-5c22-471b-9e5b-a444982af327.png">

**Comment by Mashhood-Ehsan** [comment]
This is fine now, so closing this bug.

![Screenshot (1455)](https://user-images.githubusercontent.com/60692597/199333357-967ab98a-ad54-4bce-b515-42d33b1907ed.png)
