### ISSUE TITLE
Profile > Banner Picture > System is cutting the banner image (not fully displaying it), and also its pixels are distorted. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#138]
![3](https://user-images.githubusercontent.com/60692597/198098853-22d99527-f835-4495-a77c-e14c339f83c5.PNG)

**Comment by bioworkflows** [comment]
OK, the scaling / cropping algorithm has been revised.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it.

![Screenshot (1456)](https://user-images.githubusercontent.com/60692597/199333652-025937b3-c428-4d3b-9b60-1c24dde8e78a.png)
