### ISSUE TITLE
Purchased Workflow > For free workflows, 'Request a Refund' button should not be there. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#142]
![6](https://user-images.githubusercontent.com/60692597/198103092-996fdbf1-6218-4cc5-9b80-1edc1d233ef0.PNG)

**Comment by BoPeng** [comment]
Agree, but there should be some way to "return" the workflow so that it no longer shows in the purchased page.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![Screenshot (1453)](https://user-images.githubusercontent.com/60692597/199332805-71b797bb-36f7-42bf-8bad-f5e9a8629dc2.png)
