### ISSUE TITLE
Search > Advance search > In actual "workflow 1" exists in system, but system is displaying a wrong message regarding that search. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#143]
Message: No workflow matches the description "workflow 1". Refine your search.

![screencapture-staging-bioworkflows-workflows-2022-10-26-10_10_34](https://user-images.githubusercontent.com/60692597/198103931-5134a0c6-c0e6-43ae-9d9b-db0ed4a0e292.png)

**Comment by bioworkflows** [comment]
sentence removed.

**Comment by Mashhood-Ehsan** [comment]
The "Advance Search" functionality is not working properly, the user searched for a workflow that was there, but the system did not display it. 

![Screenshot (1451)](https://user-images.githubusercontent.com/60692597/199332373-3a040b9d-42d8-4f63-acc9-5c7fd66d06da.png)

![Screenshot (1452)](https://user-images.githubusercontent.com/60692597/199332407-c33fa318-1016-48bd-8c0c-5d92419abd81.png)

**Comment by BoPeng** [comment]
THis is fixed. The problem was with backend indexing which should have done overnight.

**Comment by Mashhood-Ehsan** [comment]
Working fine now, so closing it.

![Screenshot (1463)](https://user-images.githubusercontent.com/60692597/199402508-53cb1e4c-b130-4bc8-b520-ee0600c3077a.png)
