### ISSUE TITLE
Workflow Purchase > Add to cart > Checkout button is not working, when user click on it nothing happens. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#144]
https://share.vidyard.com/watch/AMEGMRZ5cLFDqmeLa6RWVW?

**Comment by BoPeng** [comment]
ok, I noticed some mysterious clearing of carts, let me check.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed and was successfully able to purchase workflow.

![Screenshot (1450)](https://user-images.githubusercontent.com/60692597/199331690-37a88c5e-9b87-4e67-ba08-102f7d76653f.png)
