### ISSUE TITLE
Workflow Purchase > Add to cart > When user click on 'view cart' button, item gets removed from the cart on checkout page. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#145]
https://share.vidyard.com/watch/rASoGPZQLAVTd2TCUKHwW5?

**Comment by bioworkflows** [comment]
Cannot reproduce. Please provide more details such as what has been added to cart, what has been done before the steps shown in the video is performed.

**Comment by Mashhood-Ehsan** [comment]
I have added the free workflow named 'workflow 5'
Please check the attached video, everything is there.

**Comment by BoPeng** [comment]
workflow 5 was marked purchased but with no purchase history, so there was likely some inconsistency caused by all the database changes. I reset the purchase and tried again and the cart works fine. Please verify.

**Comment by bioworkflows** [comment]
What happened was likely:

1. the user has enough balance so the balance was automatically used
2. the confirmation box failed to appear so the cart was not properly displayed as empty.
3. when you click the checkout the second time, the purchase has already completed and the cart is empty.

This should have been fixed.

**Comment by Mashhood-Ehsan** [comment]
This is working fine now, so closing it.

![Screenshot (1449)](https://user-images.githubusercontent.com/60692597/199329316-a8608fd2-312d-4696-9d1e-fad37d0c91af.png)
