### ISSUE TITLE
Workflows > System is displaying the same workflow from two different users while clicking on their names

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#148]
![Screenshot (1414)](https://user-images.githubusercontent.com/60692597/198284282-0dd02bb5-2ff6-48ba-9cd0-5921b0cabfe7.png)

**Comment by BoPeng** [comment]
Those are not users, they are "teams", so the user could be member of both teams, as well as the authors of the teams, and share both workflows with the teams.

So please check if the workflows are shared to the teams.

**Comment by Mashhood-Ehsan** [comment]
Thanks for clearing up the confusion.
Yes, these were shared with the team!
So closing it.
