### ISSUE TITLE
Workflows > Upload Workflow > 'Extended License' price field should not accept text and special characters.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#150]
![8](https://user-images.githubusercontent.com/60692597/198290924-40d634d2-087b-4591-b1f9-ba3d15a0b33a.PNG)

**Comment by bioworkflows** [comment]
I did some research and saw this from https://stackoverflow.com/questions/19966417/prevent-typing-non-numeric-in-input-type-number

> Preventing users from entering a non-numeric character (i.e. BREAKING their keyboard) is not very user friendly. A user friendly approach is to allow them to type and explain what is wrong. A user that is trying to enter a string into a number input will not understand why his keyboard stopped working. I'm surprised how many developers strive to implement this anti user feature. This goes to all blocking behaviors (max-length, patterns), very non user friendly. Not to mention that users do not usually look at their screen while typing.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![Screenshot (1447)](https://user-images.githubusercontent.com/60692597/199327134-84412304-3fc3-481a-8da8-fd7f39b64244.png)
