### ISSUE TITLE
Workflow > Upload Workflow > System is giving '500 server error' on clicking the save workflow button. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#151]
https://share.vidyard.com/watch/2VanfJdZpGCa2cN5Q9n2hg?

**Comment by BoPeng** [comment]
Looks like the server is running out of diskspace. I am checking.

**Comment by bioworkflows** [comment]
I have "isolated" the index module so that its error will not affect the main app. I have not tried to free up some disk space just to test if this error will not be raised when indexing fails.

**Comment by Mashhood-Ehsan** [comment]
The system is not giving this error anymore, so closing it.
