### ISSUE TITLE
Worflow > Upload Workflow > User has edited/updated the prices, but still system keep displaying the workflow as Free. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#153]
https://share.vidyard.com/watch/H8nV8ZPrKJf3gRnCtLCcnd?

**Comment by BoPeng** [comment]
This should have been fixed.

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/9889312/198906012-e410f4e4-e4a4-4624-8a27-ad0e39749c58.png">

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it.

![Screenshot (1442)](https://user-images.githubusercontent.com/60692597/199325621-cbd46314-f7b3-400d-bfa6-f24404ea71ce.png)
