### ISSUE TITLE
Users > List > User has followed the other person, but his follower count does not get increased. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#154]
![9](https://user-images.githubusercontent.com/60692597/198849645-f19b0bc1-8e6d-4dec-af8c-ff817c1423d9.PNG)

**Comment by bioworkflows** [comment]
The side effect of making this change is that 0 followers will be displayed.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![Screenshot (1446)](https://user-images.githubusercontent.com/60692597/199326667-696383e8-05b2-4f38-8481-0293513f434f.png)
