### ISSUE TITLE
Workflow > Upload Workflow > System is displaying the same 'free workflow' two times under the purchased section. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#158]
![Screenshot (1453)](https://user-images.githubusercontent.com/60692597/199333030-85c4b7fb-78e9-473c-af69-b656daf837aa.png)

**Comment by bioworkflows** [comment]
I think this is caused by repeated buying and returning, and bug fixing in between, because these are legitimate orders for the same workflow.

<img width="2089" alt="image" src="https://user-images.githubusercontent.com/47236991/199358598-4f150e96-0987-4c4a-8b26-7e1a8d0dda9d.png">

**Comment by Mashhood-Ehsan** [comment]
Okay, understood!
