### ISSUE TITLE
Workflow > My Workflow > When user click on the 'show' option and try to open 'link in new tab', user gets redirected to the same page.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#162]
![Screenshot (1552)](https://user-images.githubusercontent.com/60692597/204156045-8c8f5258-80c6-4b98-82dc-6b6a2076eebc.png)

**Comment by BoPeng** [comment]
Thanks. This is a general problem for most menu items. It has been fixed.
