### ISSUE TITLE
Workflow > My Workflow > When user submit the workflow, system must display a sucess message/tooltip.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#164]
Example: "workflow has been submitted successfully for review"

![Screenshot (1554)](https://user-images.githubusercontent.com/60692597/204156257-984c7f20-1626-48c1-9439-5ca0b542a209.png)

**Comment by BoPeng** [comment]
the page is refreshed with a new message for "pending" status.

**Comment by Mashhood-Ehsan** [comment]
The issue is resolved, so closing it.

![Screenshot (1584)](https://user-images.githubusercontent.com/60692597/206001958-cd6f3f0f-7d9c-4da1-8a78-5b053f1ff33c.png)
