### ISSUE TITLE
Workflow > My Workflow > Under 'Seller' section, system is displaying the total workflow count as 7 but in actual system is displaying only 3 workflows. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#165]
![Screenshot (1555)](https://user-images.githubusercontent.com/60692597/204156994-13ac8b8e-f759-438e-8be8-0fc94d3f5b93.png)

**Comment by bioworkflows** [comment]
The top menu shows `DRAFT` workflows (to alert users) and the my workflow page shows all workflows. This has been clarified.

**Comment by Mashhood-Ehsan** [comment]
The issue is resolved, so closing it.

![screencapture-staging-bioworkflows-dashboard-manage-items-2022-12-07-00_16_05](https://user-images.githubusercontent.com/60692597/206002432-f7005994-e7c7-4f6c-9fe1-5de1589f79bb.png)
