### ISSUE TITLE
Workflow > Purchased Workflows > System is displaying the same purchased workflow multiple times. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#170]
![screencapture-staging-bioworkflows-orders-purchases-2022-11-28-01_25_41](https://user-images.githubusercontent.com/60692597/204158069-c83b3d02-a4cd-4684-9d18-d2884a362e6e.png)

**Comment by bioworkflows** [comment]
These are from previous purchase/refund transactions. It has been fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is resolved, so closing it.

![Screenshot (1590)](https://user-images.githubusercontent.com/60692597/206004979-96c8d0b7-17e6-418f-a2f1-f626bbaf99db.png)
