### ISSUE TITLE
Workflow > Comments > User did not get notification when someone likes/Thums-Up his/her comment. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#174]
![4](https://user-images.githubusercontent.com/60692597/204160181-99867323-a8bd-4e92-b335-5ec2e096f720.PNG)

**Comment by bioworkflows** [comment]
This fixed. However, because a new notification type is added, the one who receive notification needs to go to settings -> notifications -> reset to defaults. This will add the notification type and set it to true (default).

**Comment by Mashhood-Ehsan** [comment]
The issue is resolved, so closing it.

![Screenshot (1594)](https://user-images.githubusercontent.com/60692597/206007545-7c2f1d9f-8429-4d5b-bcde-34d1eb28e5e9.png)
