### ISSUE TITLE
Forum > Ask a question > When user add a question, system display the success message two times. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#177]
![Screenshot (1560)](https://user-images.githubusercontent.com/60692597/204305728-9d8b49f7-bc7b-4cd2-9208-97f2c97aa141.png)

**Comment by bioworkflows** [comment]
Creating a topic does not show these. I think you meant messages after updating a topic. This has been fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is resolved, so closing it.

![Screenshot (1598)](https://user-images.githubusercontent.com/60692597/206008190-173a1e79-cb05-4075-b590-466ed3f78a5b.png)
