### ISSUE TITLE
Orders > Transactions > System is displaying the same transaction multiple times under the user's dashboard

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#179]
![screencapture-staging-bioworkflows-orders-transactions-2022-11-28-22_11_16](https://user-images.githubusercontent.com/60692597/204339754-53678144-1d39-483e-8d45-a86bc02150ad.png)

**Comment by bioworkflows** [comment]
The transaction history has been cleared so this has to be confirmed and fixed later.

**Comment by bioworkflows** [comment]
The transaction page has been re-written to show orders as well as balance histories.
