### ISSUE TITLE
After avatar being updated sucessfully, the profile picture become distorted and the picture quality decreases and become blurry. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#181]
The preview looks fine, but after the avatar gets updated, the picture quality gets affected. 

https://share.vidyard.com/watch/j3HJD2vaqwowQEqYejcLMY?

**Comment by bioworkflows** [comment]
Currently, the system crop the provided image at the center according to a 1:1 aspect ratio, and then scale up to a standard size. It is possible to stop scaling up and fill the missing area with white space though.

**Comment by bioworkflows** [comment]
I will mark it as not-fix unless some better method is proposed for handling low-resolution input images.
