### ISSUE TITLE
Credt & Giftcard > The gift card which was issued to a user (user-2) should not be visible to any other user (user-1)

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#190]
In the current scenario, user's 2 gift card was also visible to user-1

![2](https://user-images.githubusercontent.com/60692597/208517872-d714623f-5537-4952-9d47-7f3db443deab.PNG)

**Comment by bioworkflows** [comment]
If I am not mistaken, the gift card is issued by the logged-in user to user2. Currently the system allows the user to convert the gift card to credit in which case the recipient can no longer redeem it.

This should be better explained, or be available only after the gift card expires.

**Comment by bioworkflows** [comment]
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/47236991/208601603-0e33c5ca-2649-4525-a10f-874c30cf2509.png">

showing expiration date and display "Convert to Credit" button only after the card is expired.

**Comment by Mashhood-Ehsan** [comment]
It's better now and understandable.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.
