### ISSUE TITLE
Community Discussion Forum > Bounty Question > User should not be allowed to enter the amount in negative value.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#191]
![1](https://user-images.githubusercontent.com/60692597/208518563-4c9ac46c-fafb-4758-b9c1-2a12bfc20ba4.PNG)

**Comment by bioworkflows** [comment]
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/47236991/208602075-9c691150-a0fd-46c3-920a-f9014fa57680.png">

but I have added the min constraint.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.
