### ISSUE TITLE
 Community Discussion Forum > Bounty Question > when user downvote a question, the count do not increase.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#192]
![5](https://user-images.githubusercontent.com/60692597/208520008-649bad8e-dced-4e41-b7b5-8285caed75f2.PNG)

**Comment by bioworkflows** [comment]
same as #188

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.
