### ISSUE TITLE
Forum > create question > UI/UX alignment issue on the keywords section. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#194]
![7](https://user-images.githubusercontent.com/60692597/208521734-03bbf43e-849b-4acc-b7c2-3c791044cd18.PNG)

**Comment by bioworkflows** [comment]
Is this Firefox? Appears to be ok here on chrome

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/47236991/208763547-8fab40ce-842e-42c2-9a3d-9a7da25b992c.png">

**Comment by Mashhood-Ehsan** [comment]
No, the attached screenshot is from chrome.

**Comment by BoPeng** [comment]
Cannot reproduce using chrome or firefox, even using the same keywords

![image](https://user-images.githubusercontent.com/9889312/209404633-14c982f9-56b8-4599-942c-8cf8a82d4a7f.png)
