### ISSUE TITLE
Profile > My Bounties > Other user's entered bounties must not be visible under the 'My Bounties' section of the user. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#195]
![8](https://user-images.githubusercontent.com/60692597/208522261-e0441c2d-9d1e-4b59-a0fb-8cc0d4f41ac6.PNG)

**Comment by bioworkflows** [comment]
Just to clarify, the list has columns

```
time, bounty poster, amount, topic
```
and contains both

1. The bounty listed by the logged in user
2. The bounty responded by the logged in user

If the highlighted bounty does meet one of the criteria, the system should be working as expected, but I will add some explanation there.

**Comment by bioworkflows** [comment]
Separated two lists

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/47236991/208780891-4b5f67e8-3b00-4751-b453-c3512e1f2b98.png">

**Comment by Mashhood-Ehsan** [comment]
It's better now,
So closing this bug.
