### ISSUE TITLE
Community Discussion Forum > Bounty Question > User is not able to upvote/downvote the reply of question. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#196]
![9](https://user-images.githubusercontent.com/60692597/208522809-1080bfa8-6988-4a62-943c-6b7e8af3c28b.PNG)

**Comment by bioworkflows** [comment]
This is by design but since only trusted users can downvote and upvote (to avoid spam), but I will add a hint.

**Comment by bioworkflows** [comment]
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/47236991/208781770-ed1ad0b7-b4cf-41a0-8b86-67e9673e9527.png">

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/47236991/208782028-5b77f65b-d29e-47bd-8c47-3970c1bb0159.png">

Add tooltip to explain why the up and down vote buttons are disabled.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.

![image](https://user-images.githubusercontent.com/60692597/209320264-b289fd8c-d935-4b64-8203-e39c6994fa6c.png)
