### ISSUE TITLE
 Community Discussion Forum > Bounty Question > The word "remain" should be replaced with "remaining"

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#197]
![10](https://user-images.githubusercontent.com/60692597/208523031-b5f8e92e-0dcc-498b-b02c-9c09e758d08a.PNG)

**Comment by bioworkflows** [comment]
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/47236991/208782290-a8d4a580-eda5-4e92-b5dd-e3cf50c77192.png">

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.
