### ISSUE TITLE
Community Discussion Forum > Bounty Question > The question did not got any upvote, but still system displaying the 'Net upvotes' as 1 under the 'My bounties' section. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#198]
![11 (1)](https://user-images.githubusercontent.com/60692597/208523307-8aa4f968-8d16-44c2-8330-c04e8fe6c08f.PNG)
![11 (2)](https://user-images.githubusercontent.com/60692597/208523324-d3f46687-0c30-489f-95ae-fb0c9356d334.PNG)
![11 (3)](https://user-images.githubusercontent.com/60692597/208523341-a533ed2c-d406-4fdd-bc21-1de893554827.PNG)

**Comment by bioworkflows** [comment]
The topic poster is wrongly counted. Should have been fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.
