### ISSUE TITLE
Dashbaord > Profile > Sometime system randomly start shwoing the incorrect profile picture on different parts of screen. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#199]
![12](https://user-images.githubusercontent.com/60692597/208523632-8b445258-e4f5-44bb-b9f6-22b85e68b092.png)

**Comment by bioworkflows** [comment]
Not sure how to reproduce this..

<img width="2087" alt="image" src="https://user-images.githubusercontent.com/47236991/208782971-73f60d95-8165-4863-a8cc-1140dd7ab8a2.png">

**Comment by Mashhood-Ehsan** [comment]
This issue occurs randomly, without following any specific steps.
also able to produce it recently too.

![15](https://user-images.githubusercontent.com/60692597/208981340-2dcc8af1-f05e-4bb6-9ba5-a36e5ebe68a4.PNG)
