### ISSUE TITLE
 Community Discussion Forum > Bounty Question > If there are tags being used inside the question, then the last reply time alignment gets disturbed. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#200]
![13](https://user-images.githubusercontent.com/60692597/208523949-bb912503-0dbd-400e-a893-6d4f9e2bd9ce.PNG)

**Comment by bioworkflows** [comment]
Moved tags to its own line

![image](https://user-images.githubusercontent.com/47236991/208822422-42636444-49bc-4bfa-ac5e-cba877f0300c.png)

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.

![Screenshot (1638)](https://user-images.githubusercontent.com/60692597/209319318-3e7b70b2-59fa-4457-8542-73ea4fc2c567.png)
