### ISSUE TITLE
Community forum > Update Reply > Data should get cleared from 'update reason' field, once user save the update reason. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#204]
![22](https://user-images.githubusercontent.com/60692597/208978628-91c61990-5af9-4a15-961b-e0e82de9c2c6.PNG)

**Comment by bioworkflows** [comment]
This is indeed confusing, but technically speaking, the "update reason" is saved as the "post" as the last update reason, so it is reasonable to update the "update reason" if needed.

Anyway, I have removed this fixed since it is not used anywhere else (for now).

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.
