### ISSUE TITLE
Community Discussion forum > A bounty has gotten an upvote but system still showing the 'There is no eligible upvote for bounty yet' notification under my boubties section..

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#206]
![19 (1)](https://user-images.githubusercontent.com/60692597/208979080-97041e7a-2641-4ab2-83dc-59d5af804254.PNG)

![19 (2)](https://user-images.githubusercontent.com/60692597/208979098-3ca3703c-0a80-4388-b0f9-e2517f7fa371.PNG)

**Comment by bioworkflows** [comment]
The same as #209?

**Comment by Mashhood-Ehsan** [comment]
Even though the pages are different, I think the issue is the same.
So closing it.
