### ISSUE TITLE
Community Discussion Forum > system is displaying the bounty amount in negative value under the bounties detail section.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#207]
![17](https://user-images.githubusercontent.com/60692597/208979466-b49ac5e3-ec4b-4812-8b65-7002dd7233ed.PNG)

**Comment by bioworkflows** [comment]
This is caused by wrongful adjustment of topic bounty when individual bounties are added and removed. It has been reset to correct value and we should not see this anymore.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.

![image](https://user-images.githubusercontent.com/60692597/209317242-e0f2df1f-0fe7-4931-b7a4-dd59b21e416e.png)
