### ISSUE TITLE
Community Discussion forum > A bounty has gotten an upvote but system still showing the 'There is no eligible upvote for bounty yet' message alon with bounties.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#209]
![18 (1)](https://user-images.githubusercontent.com/60692597/208980310-807f8d61-4e91-4b8e-9449-33ae4aaab3b0.PNG)
![18 (2)](https://user-images.githubusercontent.com/60692597/208980335-20e3d82d-0fb3-425e-aa8c-72676895358a.PNG)

**Comment by bioworkflows** [comment]
That upvote is for the question itself, it is not an upvote for an answer. Also, answers by the question poster themselves are also ignored (bounty poster cannot claim his own bounty).

I will explain this in more detail.

**Comment by Mashhood-Ehsan** [comment]
As per the comments, and observing the system behavior. closing this bug.
