### ISSUE TITLE
My bounties > When the bounty time period gets over, system must cancel the bounty instead of displaying '0 minutes'

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#210]
![15](https://user-images.githubusercontent.com/60692597/208980811-7729a5c3-929d-4c6b-b8c2-c11e5719a429.PNG)

**Comment by bioworkflows** [comment]
Changed to `expired`.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.
