### ISSUE TITLE
My Bounties > When user withdraw a request, some kind of sucess message should be generated. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#211]
![23](https://user-images.githubusercontent.com/60692597/208986310-31a84bf4-9fff-43a4-a78f-a0ed14dda43d.PNG)

**Comment by bioworkflows** [comment]
Added.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.
