### ISSUE TITLE
forum > blog > No matter how many words user has entered but system keep displaying '1000 characters remaining'. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#213]
![1](https://user-images.githubusercontent.com/60692597/215350868-fe749d7d-4a3c-4491-99ce-3d56dc2b9754.PNG)

**Comment by bioworkflows** [comment]
Fixed. Also added character remaining count for workflow review.

**Comment by Mashhood-Ehsan** [comment]
The remaining characters are not visible. 

![8](https://user-images.githubusercontent.com/60692597/219971633-758be3b2-3786-4d48-b904-ef66a4bf3b5c.PNG)

**Comment by bioworkflows** [comment]
I see.  I fixed the counting for reviews and workflow comments, but not blog comments. Fixed now. 

I also added the capacity for users to update and remove comments.

**Comment by Mashhood-Ehsan** [comment]
The issue is being resolved, so closing it.

![Screenshot (1804)](https://user-images.githubusercontent.com/60692597/220170804-99b3ab2b-cade-4b37-9ca8-65eb81909863.png)
