### ISSUE TITLE
Forum > Blog > When admin make changes/edit the blog, it gets unpublished and removed from clinet. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#214]
It would be better to keep the old version (before editing) on the client side and to push the new version once the changes are done. 

![3](https://user-images.githubusercontent.com/60692597/215351570-fb3fc16b-7738-4f72-8e29-ed6e1a7b4943.PNG)

![3 (2)](https://user-images.githubusercontent.com/60692597/215351580-b14fc135-f795-4d4d-a1b8-fd447d75fe7f.PNG)

**Comment by bioworkflows** [comment]
blog now retains its published status (or unpublished status) after update.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it. 

![10](https://user-images.githubusercontent.com/60692597/219972050-64bb74b2-b3e8-44d6-ae75-58c1fd4f3145.PNG)
