### ISSUE TITLE
Forum > Blog > Picture preview is not availble and also the link is not clickable. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#216]
![4](https://user-images.githubusercontent.com/60692597/215502463-614b932b-9dd4-445f-ba9b-fe605b1ac8e0.PNG)

**Comment by bioworkflows** [comment]
This looks like the same as #224 .

**Comment by Mashhood-Ehsan** [comment]
The issue is already discussed and resolved, so closing it.
