### ISSUE TITLE
Signout > When user sign out of the web application, system start displaying the 'Sign out' button at top left corner.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#218]
![6](https://user-images.githubusercontent.com/60692597/215605751-708518f2-ddcf-410f-9c00-0ff5e685143b.png)

**Comment by bioworkflows** [comment]
I cannot reproduce this. When the menu item is clicked, the system is supposed to replace the menu with something like 'Signing Out' then refresh to home screen. It is rather quick so I cannot see the "Signing Out" text.

Maybe you used another method to log out? Could you elaborate?

**Comment by Mashhood-Ehsan** [comment]
Not able to reproduce it anymore, so closing it.
