### ISSUE TITLE
Orders >  Shopping Cart >Checkout functionality is not working, when user click on the 'Proceed to checkout' nothing happens/.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#220]
![8](https://user-images.githubusercontent.com/60692597/215873130-cefb77b1-7e5d-4041-a1e0-43e5ddfda8bd.PNG)

**Comment by Mashhood-Ehsan** [comment]
The user has started navigating to the striped screen, but nothing happens. And the stripe screen keeps loading. 

![5](https://user-images.githubusercontent.com/60692597/219970568-12351301-5f6e-4b3a-b54c-fbbde013b7e7.PNG)

**Comment by BoPeng** [comment]
ok, this might be a problem with the specific user with invalid link to stripe. I have reset stripe id for user shami5 and tried to make a purchase successfully. Could you try again?

**Comment by Mashhood-Ehsan** [comment]
Below is the latest attached artifact:

https://share.vidyard.com/watch/S7ktE4YaTfB8B79KqLZyXM?

**Comment by BoPeng** [comment]
I can see the payment page on my end for the same type of transaction, but payment failed anyway. Let me check.

<img width="2159" alt="image" src="https://user-images.githubusercontent.com/9889312/220249225-8b4e914d-6e96-4f9d-a769-d5258689e313.png">
