### ISSUE TITLE
Upload Workflow : Title should be of max '256 characters', but user is able to enter the text logner than defined characters numbers. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#221]
![9](https://user-images.githubusercontent.com/60692597/215875424-831ac54d-4ecb-4ddb-9c1e-5b4398dd9a10.PNG)

![10](https://user-images.githubusercontent.com/60692597/215875474-f45a320c-1913-4be3-a553-0da1bc19f41a.PNG)

**Comment by bioworkflows** [comment]
What browser are you using. This widget is defined with `maxlength="256" and my browser does not allow me to enter more than 256 characters.

```html
<input type="text" name="title" maxlength="256" minlength="5" class="form-control" placeholder="Enter the title of your workflow..." id="id_title">
```

**Comment by Mashhood-Ehsan** [comment]
I'm using the Chrome Web Browser.

**Comment by bioworkflows** [comment]
Are you sure your text is longer than 256 characters? Please enter the title in text form so that I can count.

**Comment by Mashhood-Ehsan** [comment]
The same solution goes for this just like '232', so closing it too

![Screenshot (1805)](https://user-images.githubusercontent.com/60692597/220172783-51570020-c0e0-4a38-9e26-924f524234e4.png)
