### ISSUE TITLE
Upload Workflow > If user switch to the toggle view option, system do not correctly display the inseted image. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#224]
![13](https://user-images.githubusercontent.com/60692597/216755236-a0d3699b-ab84-4d1c-8768-f9cb72471652.PNG)

**Comment by bioworkflows** [comment]
What syntax did you use? I used 

```
![description](https://www.wikihow.com/images/thumb/f/fc/Get-the-URL-for-Pictures-Step-1-Version-6.jpg/aid597183-v4-728px-Get-the-URL-for-Pictures-Step-1-Version-6.jpg.webp)
```

and it works fine

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/47236991/218360677-c672328b-4951-4061-8448-9c8a1047c7d9.png">


<img width="1237" alt="image" src="https://user-images.githubusercontent.com/47236991/218360693-99be7b31-6c89-4c24-a48b-2f6721765eb4.png">

**Comment by Mashhood-Ehsan** [comment]
I was using the wrong syntax, with the new syntax you mentioned above the issue is being resolved. 

![6](https://user-images.githubusercontent.com/60692597/219970896-dddb4b1f-ffe2-498e-9e00-d76607daf0a2.PNG)
