### ISSUE TITLE
Workflow > View Details > 'Slug' is causing confusion, Better to replace this with Name/Title. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#226]
If you wanted to keep the slug, then replace the slug and the Title should be the same. Like there is no need to put a hyphen (-)

![15 (1)](https://user-images.githubusercontent.com/60692597/216755404-9340dbc5-bf34-46f1-8a4c-1f38df5e12f4.PNG)

![15 (2)](https://user-images.githubusercontent.com/60692597/216755409-1b085aa2-e233-4f2e-b6e6-68784ad9430f.PNG)

**Comment by bioworkflows** [comment]
Changed to 'name', which is a shorter version of the title.

**Comment by Mashhood-Ehsan** [comment]
The issue is resolved, so closing the bug.

![3](https://user-images.githubusercontent.com/60692597/219969687-cd309641-24ec-49ce-9bc3-5ee7f85018da.PNG)
