### ISSUE TITLE
Tracking > Recent Messages > Cross Icon (X) is not working. When user click on it nothing happens. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#229]
![19](https://user-images.githubusercontent.com/60692597/216757329-9f23caf2-6452-4fae-9a83-6e0f5f48c082.PNG)

**Comment by bioworkflows** [comment]
Removed the cross from the list because it should not do anything  (the history will always be there), but I have fixed the button from the header list. The button will remove the item from the list although kind of temporary since refreshing the page will bring the items back.

**Comment by Mashhood-Ehsan** [comment]
The issue is resolved, so closing it.

![2](https://user-images.githubusercontent.com/60692597/219969558-f0caa8a5-76fb-4e3d-9f56-937be62a4dc0.PNG)
