### ISSUE TITLE
Workflow > Share with team > User has shared a workflow with team, but the team has not received any notification regarding to this activity. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#231]
![16 (1)](https://user-images.githubusercontent.com/60692597/216757849-7329c067-758a-4724-a7da-80c10ba302ca.PNG)

![16 (2)](https://user-images.githubusercontent.com/60692597/216757853-a05adead-7069-47b9-a79e-40b5a3a05711.PNG)

**Comment by bioworkflows** [comment]
Fixed.
