### ISSUE TITLE
Upload Workflow > User has entered '213 characters' in the title, but after saving the workflow it showing only '158 characters'

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#232]
As the limit is '256 characters' the system must display all the characters if it's below that number.

![21 (1)](https://user-images.githubusercontent.com/60692597/216758766-f7c00160-f0ac-4671-924c-14b9f5141e0a.PNG)

![21 (2)](https://user-images.githubusercontent.com/60692597/216758770-85746cbe-71cd-4994-b513-747b5fa25f09.PNG)

**Comment by BoPeng** [comment]
I tried using a 256 character title "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor velit vel dolor consequat, a tempor sem lobortis. Aliquam erat volutpat. Nulla eget faucibus nisi, non blandit ex. Curabitur bibendum enim vel dui consectetur, eu pharetra ligula tincidEND" and it is display in full

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/9889312/218268229-f89dd001-d1d9-4ff9-9fd5-4b2e00484fbf.png">

**Comment by Mashhood-Ehsan** [comment]
The number of characters in the sentence that you have given is 117.

**Comment by bioworkflows** [comment]
```
>>> len('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor velit vel dolor consequat, a tempor sem lobortis. Aliquam erat volutpat. Nulla eget faucibus nisi, non blandit ex. Curabitur bibendum enim vel dui consectetur, eu pharetra ligula tincidEND')
256
```

**Comment by Mashhood-Ehsan** [comment]
I have realized and understood now, how it's working. It basically cut the text to 256 charters. 

So closing this bug now, no need to investigate further. 


![Screenshot (1805)](https://user-images.githubusercontent.com/60692597/220172640-b940564a-56cf-43d2-8c15-7bba73601474.png)
