### ISSUE TITLE
Open website > Propose a workflow >  When user click on the 'extract meta data' button, system start giving an error pop-up. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#233]
![1](https://user-images.githubusercontent.com/60692597/236696162-28ba79ae-50b9-4644-b64a-51b0f7fdf9ac.PNG)

**Comment by bioworkflows** [comment]
Focus. This is the focus of development with no testing yet.

**Comment by Mashhood-Ehsan** [comment]
The issue is being resolved, so closing the defect.

![10](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/d361d798-c9bf-4e44-86b1-d3a31b705b49)
