### ISSUE TITLE
Worflow > Propose a workflow > when user click on cross icon (x) and try to cancel it. It dont get cancel actually and system again started shoiwng an error 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#234]
![2](https://user-images.githubusercontent.com/60692597/236696209-105110d8-45a9-49ef-8edd-e6720b509b21.PNG)

**Comment by BoPeng** [comment]
The icon means some error has happened and an alert was triggered to show the error. Not sure what other UI/UX should be used here.

**Comment by Mashhood-Ehsan** [comment]
My bug was related to the cross icon (X), I'm trying to understand its purpose. 
From user's perspective, it seems that when the user clicks on this cross icon (x), the error pop-up will goes out.
But in actual what was happening, when user click on it, it again started loading the same error.

**Comment by bioworkflows** [comment]
Use toast window instead of alert, and stopped using x mark.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect.

![10](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/8232c0e9-d0ba-4521-bd72-e39d5c48352e)
