### ISSUE TITLE
Workflow > Propose a new workflow > The banner's image preview should only be available on the 'banner image' section not in the 'jupyter notebook' section. As its confusing the end-user. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#235]
![3](https://user-images.githubusercontent.com/60692597/236696316-1be74624-da2a-4344-bd97-b836aac59c90.PNG)

**Comment by BoPeng** [comment]
So the layout is messed up... And some figures are not previewed, displayed. Please note the url you use and I will try to reproduce.

**Comment by bioworkflows** [comment]
No preview for other two boxes now.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect.
