### ISSUE TITLE
Workflow > Propose workflow > System is displaying same 'set banner image as default' option radio buttons three times. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#236]
![4](https://user-images.githubusercontent.com/60692597/236696418-e506ec95-e53c-45a6-9b16-3a03c42570be.PNG)

**Comment by BoPeng** [comment]
@Mashhood-Ehsan could you elaborate how you end up with these images all over the places? The system is designed to only show preview of banner images, not for main document etc. Actually the main document is not supposed to accept images.

**Comment by bioworkflows** [comment]
@Mashhood-Ehsan Please let me know if this problem persists after #235 is fixed

**Comment by Mashhood-Ehsan** [comment]
The system is displaying the banner image preview inside the 'Jupyter Notebook' section.

![16](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/b5520cb1-7483-4659-92b0-96c7afa98478)

**Comment by bioworkflows** [comment]
I cannot reproduce it. Could you share the steps to cause this?

**Comment by Mashhood-Ehsan** [comment]
Please check the attached video:

https://share.vidyard.com/watch/hHk487qAuFVRDwaei6JDfW?

**Comment by bioworkflows** [comment]
Thanks! Let me try to reproduce it.

**Comment by bioworkflows** [comment]
Ok, the problem happens only after the main document is uploaded. It is a bug from upstream and I have fixed it.

**Comment by Mashhood-Ehsan** [comment]
The defect has been fixed now, so closing it.

![17](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/80589773-efcd-408f-b51b-d2d4954c34ca)
