### ISSUE TITLE
Workflow > Propose workflow > When user upload an image/picture in the description, system convert the whole image into text and started counting those characters under text limit. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#237]
Apart from the image, the description's actual length was approx 100 characters. 

Note: This issue gets resolved when we remove the picture/image.

![5 (1)](https://user-images.githubusercontent.com/60692597/236696503-211a5d9d-0601-4926-a517-27e257b83fde.PNG)

![5 (2)](https://user-images.githubusercontent.com/60692597/236696507-6e8f19de-dd0a-4553-b111-413429408e00.PNG)

**Comment by bioworkflows** [comment]
Oh, these are embedded images and could be very large. Maybe there should not be any limit...

**Comment by BoPeng** [comment]
Maybe we should try to use uploaded image...
<p><img src="blob:https://bioworkflows.com/bba178c4-9d9b-4a78-8e11-35886e862ca9" /></p>

https://www.tiny.cloud/docs/demo/local-upload/ is the setting

**Comment by Mashhood-Ehsan** [comment]
This issue is now resolved, so closing the defect.
