### ISSUE TITLE
Forum > Bounty > 'Add a bounty' hyperlink option is not working. when user click on it nothing happens. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#242]
![8](https://user-images.githubusercontent.com/60692597/236698935-6915b46a-df8b-490a-a289-65e3bd9468ed.PNG)

**Comment by bioworkflows** [comment]
The entire description is for the previous version of the implementation and is outdated.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect.
