### ISSUE TITLE
Workflow > View > The copied url does not contain the correct/valid link fo the workflow

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#245]
![11](https://user-images.githubusercontent.com/60692597/236701582-ccf7e689-cc5b-4e64-b28c-243604ab0ff3.png)

**Comment by bioworkflows** [comment]
The text is

```
[<img alt="bioworkflows" src="https://staging.bioworkflows.comhttps://staging.bioworkflows.com/static/img/badge_icon.7f59044f70ca.svg" height="20px">](https://staging.bioworkflows.com/testqa/workflow-1.1/)
```

which should display an icon when put inside a markdown editor such as this box

[<img alt="bioworkflows" src="https://staging.bioworkflows.comhttps://staging.bioworkflows.com/static/img/badge_icon.7f59044f70ca.svg" height="20px">](https://staging.bioworkflows.com/testqa/workflow-1.1/)

The icon link somehow does not though.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect.
