### ISSUE TITLE
Forum > Workflo support > When user click on 'Request Service' button, nothing happen and user gets scroll up little bit. apart from that system dont display any sucess or error message. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#247]
https://share.vidyard.com/watch/7tMkEGNcK2XvHmVptLCjoV?

**Comment by BoPeng** [comment]
I cannot reproduce your problem and I notice that your current user is `admin`, who has special properties and will never request service. Could you try the steps with normal users?

**Comment by Mashhood-Ehsan** [comment]
For normal user, its working fine, so closing the defect.
