### ISSUE TITLE
Tags > List > User is not able to change the missing description for the keyword.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#249]
https://share.vidyard.com/watch/TQQMjN3i5vR8MEbqCMor8W?

**Comment by Mashhood-Ehsan** [comment]
"Confirm proposed revision" button is not working, when user click on it, no changes being saved. 

![5](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/554ed882-b09b-4c7f-9eb8-cb1d02d37e26)

**Comment by BoPeng** [comment]
This is because when a published tag is revised, the oroginal one is not touched. The new one is saved to "under review" section of the page and will replace the old one once it passes review. I have revised the interface to navigate to the "under review" page when the revision is submitted.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect.

![Screenshot (2143)](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/83d8149a-8cb2-4835-b517-fdebf997d745)
