### ISSUE TITLE
Orders > Purchases >The workflow was being purchased on 11th May, but system is showing the date as 10th May. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#250]
![Screenshot (2116)](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/7ccd4d0c-73a4-4061-bcd9-6421e964f08e)

**Comment by bioworkflows** [comment]
ok, this is an interesting issue of timezone. Since it is too difficult to resolve, I will just use relative time (... ago) to display all time and dates.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect.
