### ISSUE TITLE
Workflow > Keyword > User is trying to enter new keyword by putting the Prefix keyword with topic/,  tool/,  but system is not displaying the full word and only displaying the few characters.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#255]
Give you example, I have put "tool/test123", but after I pressed enter it only displayed "tool/" which is incorrect.

![19](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/4665ac18-eb16-4ce4-91b1-40f0d4dfaab3)

**Comment by Mashhood-Ehsan** [comment]
This issue is still not get resolved, and the user is not able to add a new tag, using the defined prefixes:

![4](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/110ef502-70dc-49e7-ade5-654f0f021a09)

**Comment by bioworkflows** [comment]
Interesting, I notice that if I enter `topic/something` and hit enter immediately, the option is not displayed. However, if I wait a few seconds to let `topic/something` appear in the list, it can be added.

**Comment by bioworkflows** [comment]
https://github.com/select2/select2/issues/4854

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved.

![Screenshot (2144)](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/3b0b7722-c47a-4a26-8ab9-80246c11753d)
