### ISSUE TITLE
Workflows > Add Workflow > Workflow edit functionality is not working correctly, user tried to add banner, attachemnt images but they are not being uploaded. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#262]
Samewise Jupyter file is also not being uploaded. 

https://share.vidyard.com/watch/5Ztuyhcg37bMwTH1B9MarA?

**Comment by bioworkflows** [comment]
please try again.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect after verification.
