### ISSUE TITLE
Dashboard > My workflows > Although user has only selected 'archived' workflows filter but system is still displaying published/draft options. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#263]
![1](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/11c3edd1-8fea-4720-ad92-9ab750619cfb)

**Comment by bioworkflows** [comment]
I think this is ok because it just shows the number of workflows at different statuses. The icons appears to be clickable but it is not (this has been fixed).

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect after verification.
