### ISSUE TITLE
Users > List > Although there is a seller available, but system is displaying zero (0) seller on the page. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#264]
![2](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/35e2283f-89a4-4baf-aceb-61c8061541c4)

**Comment by bioworkflows** [comment]
Please let me know which user is a seller and is not listed.

**Comment by Mashhood-Ehsan** [comment]
testqa

**Comment by BoPeng** [comment]
![image](https://github.com/bioworkflows/bioworkflows-help/assets/9889312/b8dfc185-d5d6-452b-9e38-f4bed3fe36aa)

So the seller status might have been lost during testing or database reset.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect after the verification.
