### ISSUE TITLE
Dashboard > Click on bioworkflows logo > System shows 'ProgrammingError at /dashboard/' when user click on the bioworkflows website logo.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#268]
![6](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/fb54927d-b403-4d1b-94df-1cc9d5dc4324)

**Comment by bioworkflows** [comment]
cannot reproduce. Should be related to a recent change to database.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect after verification.
