### ISSUE TITLE
Home > Dashboard > Settings > User is unable to add areas of experties due to UI/UX Issue.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#27]
![3](https://user-images.githubusercontent.com/60692597/140568182-0467b314-204a-46ac-9eab-62cd16aefe99.PNG)

**Comment by BoPeng** [comment]
Fixed. Close after you confirm.

**Comment by Mashhood-Ehsan** [comment]
yes, it is fixed. Closing it.
