### ISSUE TITLE
Workflows > Return workflow > User has requested to return the workflow, but the particular user who own the workflow did not receive any notification. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#270]
![7](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/e7df26eb-a5c6-4edc-bb2d-febafd270176)

**Comment by bioworkflows** [comment]
Works now

<img width="1911" alt="image" src="https://github.com/bioworkflows/bioworkflows-help/assets/47236991/1ac2bcc7-3c9a-47f0-b434-3f43b7982625">

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect after verification.
