### ISSUE TITLE
Forum > Questions > User is not able to upvote and downvote the other user's questions. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#272]
![9](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/d6516803-9fcc-43e8-b027-cda25ed5ba7f)

**Comment by bioworkflows** [comment]
This is by design since "novice" users are not allowed to upvote or downvote topics and questions, so avoid spamming.

**Comment by Mashhood-Ehsan** [comment]
As per the above comments, closing the defect.
