### ISSUE TITLE
Workflow > Add workflow > 'Submit for Review' button is not working, when user click on it nothing happens. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#275]
![11](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/b9e087a3-8142-4d20-8263-12a26cdb633d)

**Comment by bioworkflows** [comment]
This should work now.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect after verification.
