### ISSUE TITLE
Admin > Approve Reviews > when admin approve the reviews, system don't display any success message and ui/ux of the approve button also gets disturbed. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#278]
![14](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/ec099810-f594-4ad0-8d21-e388167f4668)

**Comment by bioworkflows** [comment]
If this is for the review of workflow reviews, it must have been fixed (forgot to add the fixed tag).

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect after the verification.
