### ISSUE TITLE
Workflow > Add workflow > User has set the pricing of workflows, but system is not showing that pricing and considering the workflow as free. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#280]
https://share.vidyard.com/watch/qLzEkYfrrPDhZ2nFY3tivZ?

**Comment by bioworkflows** [comment]
This is a problem with no license being set.

**Comment by BoPeng** [comment]
OK, this is due the open license that the user selects, I will disallow setting price for this license.

**Comment by Mashhood-Ehsan** [comment]
The pricing is not available anymore.

![21](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/10884f45-2c6e-4f1b-a6e1-f7725a571506)

**Comment by bioworkflows** [comment]
This is for anonymous upload so no pricing is allowed.
