### ISSUE TITLE
Dashboard > Transactions > System just keep loading and don't display Balance Transactions

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#282]
![16](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/9b360ae0-ef6a-4d6a-a469-50d3ef78a278)

**Comment by bioworkflows** [comment]
This is because the stripe customer is removed for this user due to the removal of stripe debug database. I have re-created the customer but the old transactions have been lost.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect after verification.
