### ISSUE TITLE
Account > followers > System is displaying same '1000Genomes' option two times. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#283]
![17](https://github.com/bioworkflows/bioworkflows-help/assets/60692597/800fe78a-b1fd-44a9-b6b9-dec7c492cc26)

**Comment by bioworkflows** [comment]
This is because `1000 genomes` appears both as `expertise` and `tools authored` for the user. This should not be allowed.

**Comment by Mashhood-Ehsan** [comment]
The issue is now resolved, so closing the defect after verification.
