### ISSUE TITLE
signature for tool/bioconda/spaln

### ISSUE THREAD

**Issue by BoPeng** [bioworkflows/bioworkflows-help#289]
<img width="959" alt="image" src="https://github.com/bioworkflows/bioworkflows-help/assets/9889312/1a409dc2-6b19-400d-872b-02a32e233b87">

The proposal to remove spaln and add spaln_add_exons.pl is problematic since spaln is a valid command. Please add the perl script in the `name1|name` format.

**Comment by faiqatariq** [comment]
Done adding spaln.
But i cant find "perl" in tag list what to do with it?

**Comment by bioworkflows** [comment]
The perl script means `spaln_add_exons.pl`. If this package has multiple perl scripts, and the `spaln` command itself, its signature should be something like `spaln|spaln_add_exons.pl|spaln_another_script.pl`.

**Comment by faiqatariq** [comment]
Got it
