### ISSUE TITLE
signature of SED

### ISSUE THREAD

**Issue by bioworkflows** [bioworkflows/bioworkflows-help#293]
signature of tool/biotools/SED is set to `sed`, which conflicts with a common linux command. 

<img width="1435" alt="image" src="https://github.com/bioworkflows/bioworkflows-help/assets/47236991/2468363f-45db-437f-b08a-58332d87f316">

However, if we check the documentation for SED,  https://seq2fun.dcmb.med.umich.edu//SED/, the real usage should be something like

```
python DeepNeuralNetTrain.py
```

We need to revert the previous signature. Which workflow did you find the use of `SED`?

**Comment by bioworkflows** [comment]
I have removed SED from all snippets and changed the signature of SED.

@faiqatariq Please try to check if the tag actually corresponds to a code snippet before adding signature. The description of this tag does not appear to be related to the workflow anyway.

**Comment by faiqatariq** [comment]
In addition to the snippet u sent "sed" has been used in some other code snippets even at the start of the script, that's why i added it as a tag.

**Comment by bioworkflows** [comment]
`sed` is a common linux command for processing text file and needs not to be tagged. SED is actually a collection of python scripts.
