### ISSUE TITLE
signature of bioconductor tools

### ISSUE THREAD

**Issue by bioworkflows** [bioworkflows/bioworkflows-help#294]
<img width="1420" alt="image" src="https://github.com/bioworkflows/bioworkflows-help/assets/47236991/671d4d89-4207-46a2-8de3-a7ce74ec0164">

Please let me know what workflow use these tools in the `bioconductor-xxxx` form. These library belong to a `bioconductor`, a collection of R packages, and are never used in such a format.

Again, the signature should be the actual pattern in code snippet to indicate the use of tagged tools.

**Comment by faiqatariq** [comment]
https://bioworkflows.com/public/nanoseq.1/ 
This workflow used these commands at the end of some snippets that's why I added.

Let me know if all the commands written at same place at them should be tagged or not?

**Comment by faiqatariq** [comment]
https://bioworkflows.com/public/scflow.1/
Should I add all the "scflow" scripts used in code snippets in this workflow?

**Comment by faiqatariq** [comment]
Grant access to more workflows pls? 
Already done with 10 workflows
