### ISSUE TITLE
Process galaxy workflows

### ISSUE THREAD

**Issue by bioworkflows** [bioworkflows/bioworkflows-help#295]
* [x] https://bioworkflows.com/public/galaxy-protein-conformational-ensembles-generation.1/
* [x] https://bioworkflows.com/public/gtn-training-antibiotic-resistance-detection.1/
* [x] https://bioworkflows.com/public/gbif-data-quality-check-and-filtering-workflow-feb.1/
* [x] https://bioworkflows.com/public/trio-analysis.1/
* [x] https://bioworkflows.com/public/biomarker-screening-in-preeclampsia.1/
* [x] https://bioworkflows.com/public/galaxy-abc-md-setup-tutorial.1/
* [x] https://bioworkflows.com/public/galaxy-amber-protein-ligand-complex-md-setup-tutor.1/
* [x] https://bioworkflows.com/public/galaxy-amber-protein-md-setup-tutorial.1/
* [x] https://bioworkflows.com/public/galaxy-protein-ligand-docking-tutorial-fpocket.1/
* [x] https://bioworkflows.com/public/galaxy-protein-ligand-complex-md-setup.1/
* [x] https://bioworkflows.com/public/galaxy-gmx-automatic-ligand-parameterization-tutor.1/
* [x] https://bioworkflows.com/public/galaxy-protein-md-setup-tutorial.1/
* [x] https://bioworkflows.com/public/population-and-community-metrics-calculation-from.1/
* [x] https://bioworkflows.com/public/climate-climate-101.1/
* [x] https://bioworkflows.com/public/pathway-ranker.1/
* [x] https://bioworkflows.com/public/retrosynthesis.1/
* [x] https://bioworkflows.com/public/genetic-design.1/
* [x] https://bioworkflows.com/public/pathway-analysis.1/

**Comment by bioworkflows** [comment]
These workflows are from galaxy so they do not have any code snippet. Please

1. Click the "workflowhub" url from the reference section, NOT the view workflow URL.
2. Add a few tags according to the steps listed at the workflowhub page. For example, for https://workflowhub.eu/workflows/4 , you will see familiar names such as FastQC, samtools, and NanoPlot.  You have to add the tags to workflows manually.
3. Add a topic tag to the workflow.
4. submit for review.

**Comment by faiqatariq** [comment]
Ok I'll follow these steps

**Comment by bioworkflows** [comment]
There are 18 left. I updated the list.
