### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by faiqatariq** [bioworkflows/bioworkflows-help#297]
TransDecoder is added to every code snippet as a tag, I don't know if it's a bug or something.

**Comment by BoPeng** [comment]
Because you have `||` in the signature, which matches blank string. Please fix the signature.

**Comment by faiqatariq** [comment]
ok. 
in https://bioworkflows.com/public/metaboigniter.1/ the code snippet has scripts like cvfilter.r,dilutionfilter.r etc. do they need to be tagged?

**Comment by faiqatariq** [comment]
grant access pls

**Comment by faiqatariq** [comment]
i think the request for access is not sending, it is not showing the notification after hitting the "request for access" button

**Comment by BoPeng** [comment]
Sorry for the delay in getting back to you. I was/am on the road and will get back to you this evening.

**Comment by BoPeng** [comment]
@faiqatariq There was a server issue (database crash). The server is up and running although we have not figured out what went wrong.
