### ISSUE TITLE
Implement auto-snippet detection for bpipe

### ISSUE THREAD

**Issue by BoPeng** [bioworkflows/bioworkflows-help#301]
https://gitlab.rlp.net/imbforge/NGSpipe2go/-/blob/master/pipelines/scRNAseq/tenX.pipeline.groovy

https://bioworkflows.com/public/scrna-seq-smart-seq-2.2/

**Comment by bioworkflows** [comment]
Works with limitations:

1. For gitlab, `*.groovy` does not work
2. subworkflows cannot be detected

So basically manual addition of each URL is required.
