### ISSUE TITLE
Jupyter notebooks issue

### ISSUE THREAD

**Issue by faiqatariq** [bioworkflows/bioworkflows-help#303]
The option of "select snippets from attachments or external file" is not showing in jupyter workflows..how would I extract snippets?

**Comment by bioworkflows** [comment]
Please give more details on steps to reproduce this, what workflow etc.

**Comment by faiqatariq** [comment]
https://bioworkflows.com/public/jupyter-amber-protein-md-setup-tutorial.1/
for example this is a jupyter notebook, the workflow does not have the option of "select snippets from attachment" so how will i able to extract the code snippets from the link

**Comment by faiqatariq** [comment]
Yes once i get the access. 
But the snippets are not extracting from the link. The page reloads and nothing happens. I tried to do it for this workflow but not working.
https://staging.bioworkflows.com/public/jupyter-notebook-protein-ligand-docking-tutorial-c.1/

**Comment by BoPeng** [comment]
What URL did you use? I enterred https://github.com/bioexcel/biobb_wf_virtual-screening/blob/master/biobb_wf_virtual-screening/notebooks/fpocket/wf_vs_fpocket.ipynb and the snippets were extracted.

You cannot use a "folder" URL.
