### ISSUE TITLE
Title, description, and banner images of workflows

### ISSUE THREAD

**Issue by bioworkflows** [bioworkflows/bioworkflows-help#307]
Please review the title, description, and banner images of workflows when you review them:

## Title

Please choose a descriptive title that describes the nature of workflow, not just the acronym to the name of workflow.

## Description

The descriptions of workflow are supposed to be a description of the 
1. background of the workflow
2. some key information such as running platforms,
3. (mostly for premium workflows later on) comparative advantage (e.g. performance) against competing workflows

It should not overlap too much with the main workflow page of the external workflows, because our description could become obsolete or inaccurate when these external workflows evolve.

## Banner images

Please remove banner images that are not informative and choose the "best-looking" one as thumbnails.

**Comment by faiqatariq** [comment]
Alright
