### ISSUE TITLE
bpipe sub workflow detection 

### ISSUE THREAD

**Issue by bioworkflows** [bioworkflows/bioworkflows-help#308]
A tutorial about bpipe workflow; according to which all files with extension .groovy have to import manually by adding URL of each file separately, but I have done so for each file but unable to import any snippets. Let's say in this case https://bioworkflows.com/public/scrna-seq-smart-seq-2.2/

**Comment by bioworkflows** [comment]
The problem with bpipe is that, for example, https://gitlab.rlp.net/imbforge/NGSpipe2go/-/blob/master/pipelines/scRNAseq/marsseq.pipeline.groovy , its subworkflow loading statement 

```
load PIPELINE_ROOT + "/modules/NGS/bamcoverage.header"
```
uses expressions and absolute path, which is difficult to grab. The only way we can think of now is to grab .groove files from the entire github repo using GitHub api but
1. it only works for GitHub (we do not yet use gitlab API)
2. it does not work well if the repository has multiple pipelines. We will have to use the load statements to filter the groovy files we find, and that over all is complicated.

For individual groovy file, we only identify exec blocks as in https://gitlab.rlp.net/imbforge/NGSpipe2go/-/blob/master/modules/ChIPseq/GREAT.groovy 

```
        exec """
            ${TOOL_ENV} &&
            ${PREAMBLE} &&

            Rscript ${PIPELINE_ROOT}/tools/GO_Enrichment/GREAT.R $GREAT_FLAGS
        ""","GREAT"

```

**Comment by twentythirdpairlab** [comment]
So here are some of the Bpipe workflows that I have found 
https://bioworkflows.com/public/scrna-seq-smart-seq-2.2/
https://bioworkflows.com/public/scrna-seq-mars-seq.1/
https://bioworkflows.com/public/dna-seq.1/
https://bioworkflows.com/public/chip-seq.1/
https://bioworkflows.com/public/rna-seq.1/

**Comment by bioworkflows** [comment]
bpipe subworkflow importing has been implemented. first workflow

```
https://gitlab.rlp.net/imbforge/NGSpipe2go/-/blob/master/pipelines/scRNAseq/essential.vars.groovy
https://gitlab.rlp.net/imbforge/NGSpipe2go/-/blob/master/pipelines/scRNAseq/marsseq.pipeline.groovy
https://gitlab.rlp.net/imbforge/NGSpipe2go/-/blob/master/pipelines/scRNAseq/smartseq.pipeline.groovy
https://gitlab.rlp.net/imbforge/NGSpipe2go/-/blob/master/pipelines/scRNAseq/tenX.pipeline.groovy
https://gitlab.rlp.net/imbforge/NGSpipe2go/-/blob/master/pipelines/scRNAseq/tenXatac.pipeline.groovy
https://gitlab.rlp.net/imbforge/NGSpipe2go/-/blob/master/pipelines/scRNAseq/tenXmultiome.pipeline.groovy
https://gitlab.rlp.net/imbforge/NGSpipe2go/-/blob/master/pipelines/scRNAseq/tools.groovy
```

**Comment by bioworkflows** [comment]
@twentythirdpairlab  We implemented an algorithm to import bpipe subworkflows and I just imported snippets for all the bpipe workflows you listed.
