### ISSUE TITLE
couldn't find snippets to extract

### ISSUE THREAD

**Issue by faiqatariq** [bioworkflows/bioworkflows-help#312]
* [x] https://bioworkflows.com/public/ejp-rd-wp13-case-study-cakut-peptidome-and-mirnome.1/
* [x] https://bioworkflows.com/public/ejp-rd-wp13-case-study-cakut-proteome-peptidome-an.1/
* [x] https://bioworkflows.com/public/permedcoe-cancer-invasion.1/
* [x] https://bioworkflows.com/public/pycompss-matrix-multiplication-out-of-core-using-f.1/
* [ ] https://bioworkflows.com/public/sorting-and-registration-of-terahertz-elbe-raw-dat.1/
 This one does not have snippet. Just removed.

**Comment by faiqatariq** [comment]
this snakemake workflow do not have any description and snippets
https://bioworkflows.com/public/pypsa-workflow.1/

**Comment by BoPeng** [comment]
https://bioworkflows.com/public/pypsa-workflow.1/ is removed.
