### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by twentythirdpairlab** [bioworkflows/bioworkflows-help#313]
**These workflows are of different type as I have also mentioned,,, how to edit them please guide!!!**

* [ ] https://bioworkflows.com/public/janis-germline-variant-calling-workflow-gatk.1/ (Janis)
* [ ] https://bioworkflows.com/public/protein-md-setup-tutorial-using-bioexcel-buildin-2.1/ (KNIME)
* [x] https://bioworkflows.com/public/protein-md-setup-hpc-tutorial-using-bioexcel-build.1/ (COMPSs)
* [x] https://bioworkflows.com/public/bootstrapping-for-bqsr-nci-gadi.1/ (Shell Script)
    use URL + '*.sh'
* [x] https://bioworkflows.com/public/delineating-regions-of-interest-for-mass-spectrome.1/ (Python)
  https://github.com/guoang4github/ROIforMSI/blob/main/ExampleWorkflow.ipynb (ipynb is recognized)
* [x] https://bioworkflows.com/public/apis-wings-eu-a-workflow-for-morphometric-identifi.1/ (R markdown)
  markdown is recognized
* [ ] https://bioworkflows.com/public/scipion-tutorial-example-reaching-2-9a-resolution.1/ (scipion)
* [x] https://bioworkflows.com/public/vip-variant-interpretation-pipeline.1/ (Unrecognized)
   These are nextflow workflows, use `https://github.com/molgenis/vip/*.nf` to get them
* [x] https://bioworkflows.com/public/rnaseq-de-nci-gadi.1/ (Shell Script)
* [x] https://bioworkflows.com/public/flashlite-supernova.1/ (Shell Script)
* [x] https://bioworkflows.com/public/flashlite-juicer.1/ (Shell Script)
* [x] https://bioworkflows.com/public/flashlite-trinity.1/ (Shell Script)
* [x] https://bioworkflows.com/public/somatic-shortv-nci-gadi.1/ (Shell Script)
* [ ] https://bioworkflows.com/public/scipion-workflow-for-cryo-electron-microscopy-of-s.1/ (scipion)
* [x] https://bioworkflows.com/public/trinity-nci-gadi.1/ (Shell Script)
* [x] https://bioworkflows.com/public/germline-shortv-nci-gadi.1/ (Shell Script)
* [x] https://bioworkflows.com/public/shotgun-metagenomics-analysis.1/ (Shell Script)

**Comment by bioworkflows** [comment]
For workflows with these scripts, use patterns like

```
https://github.com/Sydney-Informatics-Hub/Shotgun-Metagenomics-Analysis/tree/main/Scripts/*.pbs
```
where the part before `*.pbs` is legitimate URL to GitHub directory.

**Comment by bioworkflows** [comment]
I fixed most of them. The rare workflows types do not have snippets (like galaxy) so we cannot do anything about them.
