### ISSUE TITLE
Questionable tags

### ISSUE THREAD

**Issue by bioworkflows** [bioworkflows/bioworkflows-help#327]
I did not pay much attention about non-tool tags when I accept publication, this ticket will be used to list some questionable tags from @twentythirdpairlab 

* [ ] https://bioworkflows.com/public/bitextor.1/ is a pure text processing workflow. We may keep it but its operation is not "Read pre-processing".
* [ ] https://bioworkflows.com/public/rna-seq-star-deseq2.5/ 's input should be raw RNA reads (use STAR), ad output should be gene list.
* [ ] https://bioworkflows.com/public/dna-seq-gatk-variant-calling.10/ input should be raw DNA reads, not gene ID
* [ ] https://bioworkflows.com/public/dropseqpipe.1/ 's operation is not read pre-processing (maybe one of the steps is)

**Comment by twentythirdpairlab** [comment]
okay let me make changes
