### ISSUE TITLE
Tagging python libraries

### ISSUE THREAD

**Issue by bioworkflows** [bioworkflows/bioworkflows-help#329]
The following is a list of Python libraries that have been used (e.g. `import AEFilter`) but have not been tagged. Please

1. Search if they are in our tag database, if not, try to add relevant tags.
2. Once the tag is located or added, add metadata `library` with value `python:NAME`. This will set the signature for `import NAME`, `import NAME.submodule`, `from NAME import` etc.

Note that:
1. The numbers after package names are to backend use. Please ignore them.
2. Not all packages can be found because they can be locally defined packages and are not published anywhere. In this case, mark so and move on. 
3. We already tried to add packages through pypi so the names do not have direct matching entries on Pypi. However, they may come with other names from pypi or other places. For example, `vcf` may come from package `pyvcf` and tag `tool/pypi/pyvcf`.
4. If a new tag has to be added from somewhere, most likely `github`, please add `python/` before the name. For example, `MutateSeq` comes from `https://github.com/shahcompbio/mutationseq` , please add tag `tool/python/mutationseq`, and metadata `library` with value `python:MutateSeq`. 
5. Again, `python:NAME` should be the name of the library, not the distribution because `NAME` is used for matching `import NAME`. 

* [x] AEFilter 54517, 62884
* [x] DNNwERLLoss 54517, 62884
* [ ] FastDNARules 43106
* [x] GetMaxEE 54485, 54762
* [x] GetTrimParameters 54485, 54762
* [x] MultiAracne 53906
* [ ] MutateSeq 52231
* [ ] PascalX 44403, 53783
* [ ] PhysiBoSS_invasion_BB 59049
* [ ] RecBlast 54162
* [ ] SND 48946
* [ ] SNDWindow 48946
* [ ] TElocal_Toolkit 42936
* [ ] _helpers 43009, 43011, 43014
* [x] _plotters 53227
* [x] add_electricity 43297, 43307, 46620
* [x] add_existing_baseyear 57248, 58462
* [ ] admixcov 42398, 42402, 42403
* [x] adult_reduced_problem 52616, 52619, 52621
* [ ] alignment_funcs 53879, 53883
* [ ] allel 42079, 42084, 45153
* [ ] angio 50327
* [ ] annual_national_demand 54040, 56424
* [ ] apply_models 44011
* [ ] approaches 48040, 53677
* [ ] bam_to_fingerprints 51349
* [x] base_network 46629, 47782, 57301
* [ ] bigfish 42796, 47729
* [ ] bioconda_utils 57077
* [ ] biom 55240, 55241
* [ ] blast_records 47321
* [ ] build_models 44011
* [ ] build_natura_raster 58384
* [ ] build_shapes 46624, 47788, 57309
* [ ] build_tables 54238, 54248, 54264
* [ ] build_test_configs 57308, 58254
* [ ] cStringIO 62604
* [ ] cdnarules 43106
* [ ] circRNA 60899, 60900, 60904
* [ ] cleanLabFilter 54517, 62884
* [ ] clean_metadata 44015
* [ ] clinical_helpers 55237
* [ ] cluster_gas_network 57226, 58404
* [ ] codon_utils 55035, 55096
* [ ] codpos_genidx 45253, 47375
* [ ] compute_robust_exact 56301
* [ ] convert_to_nwb 43624
* [ ] convert_to_pandas 47988
* [ ] correction_files 54257, 54260
* [x] countData 57774
* [ ] custom_objective 47960, 47961, 47994
* [ ] cv2 45681, 45682, 45683
* [x] cwalk 43977
* [ ] dateutil 5283, 43300, 43859
* [ ] decode_lfads 47950, 47971, 47983
* [ ] decoding 43614
* [ ] delft3dfm_helpers 63172, 63300
* [ ] demographic_scenarios 55118, 55120, 55125
* [ ] dna_seq_analysis 63900, 63906
* [ ] docker_run 56052
* [ ] download_osm_data 46626, 47776
* [ ] encd 55471, 55476, 55479
* [ ] energy_computation 53888
* [ ] entrez_metadata 44007, 44014
* [ ] entsoe 43004, 43006, 43010
* [ ] esm 55474
* [ ] eurocalliopelib 54031, 54035, 54039
* [ ] extract_esm 55474
* [ ] extract_gb_info 58482, 58483, 58489
* [ ] extract_identifiers 59722
* [ ] fasta_from_ena 64514
* [ ] feedback_optimize_target_prediction 47954, 47955, 47959
* [ ] feems 53308, 55040
* [ ] feems_utils 55040, 55068, 55113
* [ ] filtering 43974, 43977
* [ ] filtersScikiClean 54517, 62884
* [x] fit_model 58714
* [ ] fittinglibs 49007, 49013
* [ ] friendly_calliope 54021, 54027, 54029
* [ ] functions_venn 45889
* [ ] gambit_pub 53159, 53160, 53162
* [ ] gbi_functions 54253, 54262, 54265
* [x] geffa 42916
* [ ] generate_albedo 64183
* [ ] geoutil 49118, 49119, 49122
* [ ] get_assembly_UIDs 44012
* [ ] get_gene_gtf 48285
* [ ] get_species_taxonomy 44012
* [ ] get_target_variants 54968
* [ ] gff_builder 64016
* [ ] glaes 43296
* [ ] graph_operations 54551
* [ ] gridfill 61599
* [ ] helpers_and_sources 47887, 47889, 47890
* [ ] hit_tables 51596, 51598, 62386
* [ ] homopolymers 43106
* [ ] imperatives 54253
* [ ] invasion_analysis_BB 59049
* [ ] lds_regression 47970
* [ ] lgsm 56136, 56139
* [ ] likelihood_operations 54551
* [ ] mag_annotator 43123, 57424
* [ ] make_summary 57246, 58433
* [ ] manage_assembly 44007
* [ ] masq_helper_functions 53016, 53017, 53018
* [ ] merfishtools 50676, 50687, 50689
* [ ] mergeSeqRecord 48021, 62055
* [ ] methods 56148, 56150
* [ ] modify_tense_tag 54264
* [ ] modular_theta_from_dict 51349
* [ ] mpl_toolkits 42719, 45325, 50687
* [ ] ncbi_taxdump_utils 44388, 53999, 58218
* [ ] new_predict_targets 47960, 47961, 47994
* [ ] node2vecs 43464, 43465
* [ ] normalize_species 44015
* [ ] nupack 57207
* [ ] occurence_table 48013, 48018
* [ ] omero 4581, 4596, 5317
* [ ] omero_zarr 4592
* [ ] ontSMNtools 47586, 47587, 47588
* [ ] open_gira 55923, 55925, 55926
* [ ] openeye 43038, 61529
* [ ] optimize_target_prediction 47941, 47943, 47953
* [ ] parameter_est 51349
* [ ] passion 63533, 63534, 63535
* [ ] pca_utils 55007, 55064, 55119
* [ ] peak_trainvalidtest_split 47950, 47971, 47983
* [ ] peakplotter 58634
* [ ] plot_all_controller_metrics 47983
* [ ] plot_genotype_counts 54874
* [ ] plot_helpers 61504
* [ ] plot_paper1_figs 64183
* [ ] plotting_utils 48283
* [ ] poly_A_classify 61994
* [x] polydfe_utils 55130, 55137, 55147
* [ ] prepare_sector_network 56330, 56331, 57235
* [ ] prepare_transport_data 56332, 57453
* [ ] preprocess_xsect 63952, 64183
* [ ] primer3 53884, 53885
* [ ] primer_design_functions 53015
* [ ] probe_helpers 53878, 53884, 53885
* [ ] probe_site_selection 53884
* [ ] psse35 43007, 43008, 43011
* [ ] pssgrpg 43011, 43023
* [ ] psspy 43007, 43008, 43011
* [ ] pulses_dens 44572
* [ ] pyclim_noresm 43163, 43164, 43165
* [ ] pylab 50718, 55846, 55847
* [ ] pypangraph 61459, 61461, 61462
* [ ] pyplot_settings 46274, 46275, 46276
* [ ] pyslavseq 52452, 52453, 64823
* [ ] pyvcf_utils 55134
* [ ] qiime2 41875, 41880, 55240
* [ ] renewablepotentialslib 57936, 57964, 57968
* [ ] reprosyn 47924
* [ ] retrieve_aac 45253, 47375
* [ ] retrieve_codon 45253, 47375
* [ ] rmsk_to_bed 52451
* [ ] rnaseqpoptools 48829, 48830, 48833
* [ ] root_to_tip 54872, 54877
* [ ] ruamel 46632, 57307, 57308
* [ ] running_ICA_utils 48250
* [ ] sam_to_bins_modular 51348
* [ ] scikits 49010
* [ ] script_util 56631, 56632, 63685
* [ ] segment_submovements 47939, 47948, 47952
* [ ] select_strains 58690
* [ ] seq_consensus 52946, 54812, 63281
* [ ] seqsChart 57765, 57774, 57775
* [ ] sfs_utils 55024, 55033, 55061
* [x] shapefile 63533, 63534, 63535
* [ ] skbio 55241, 57473, 58376
* [ ] sklearnFastICA 48250
* [ ] sklearn_extra 42714
* [ ] sknetwork 64702
* [ ] sksurv 48921, 48923, 48927
* [ ] smartdada2 54484, 54485, 54486
* [ ] solve_network 43711, 43714, 43715
* [ ] solve_operations 56292
* [ ] sort_rules 55237
* [ ] spec_pgram_mod 46651
* [ ] spliceai_rocksdb 42790, 42791
* [ ] splitData 48955, 61988
* [ ] srr_functions 65150, 65151
* [ ] subsample_analysis 47950, 47971, 47983
* [ ] synth_data_output 52617, 52619, 62676
* [ ] tense_rules 54256
* [ ] timing_analysis 47939, 47940, 47944
* [ ] tomopy 63994
* [x] trachoma 51977, 51981
* [x] track_hubs 64014
* [ ] undesired_subsequences 43106
* [ ] utr3variants 52984
* [ ] vcf 42234, 42241, 44482
* [ ] vcftagprimersites 44888
* [ ] verb_form 54261
* [ ] weighted_distances 58714
* [ ] workflow_utilities 56298
* [ ] xcd_plot 53890
* [ ] xnoah 63358
* [ ] yaml_io 58489, 58494, 58503

**Comment by faiqatariq** [comment]
Okay I understand, please confirm that the data will be entered this way; e.g
Library = python:Name

**Comment by BoPeng** [comment]
Small "library", not "Library".

**Comment by faiqatariq** [comment]
I have tagged all the found python libraries. Information for some commands are not available anywhere and some were not python packages so I ignored them.

**Comment by BoPeng** [comment]
Thanks. Please continue to fix short titles.
