### ISSUE TITLE
Dashboard > All Workflows > When user click on the 'Topic' drop down menu option no option appear. System only display an empty card. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#43]
![1](https://user-images.githubusercontent.com/60692597/183387775-1596da6e-6d9d-423e-a27a-46c8c3cb97e1.PNG)

**Comment by BoPeng** [comment]
This is because no `Topic` tags have been added, but we should disable/hide the dropdown anyway.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed/checked so closing it.
