### ISSUE TITLE
Dashboard > All Workflows > When user click on the cart button nothing happens.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#44]
![2](https://user-images.githubusercontent.com/60692597/183393721-0bff7cf5-c01e-4528-afaa-5f0215293d30.PNG)

**Comment by BoPeng** [comment]
ok. Click the cart icon will show cart even if there is no item in it.

**Comment by Mashhood-Ehsan** [comment]
The issue is now checked/fixed, so closing it.
