### ISSUE TITLE
User Logged In > Dashboard > If user read all the notification then system do nothing when user click on the notification icon. Even if there is no notification, user should be redirected to the notification page and system display a message like i.e. No more notifications.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#45]
![Screenshot (1074)](https://user-images.githubusercontent.com/60692597/183394930-d0618691-9110-4070-b3a2-a7209bd193cc.png)

**Comment by BoPeng** [comment]
Now click notification icon will list all notifications.

Note that this is the default behavior for cellphone since dropdown menu does not work on cellphone.

**Comment by Mashhood-Ehsan** [comment]
As per the comments, closing this bug.
