### ISSUE TITLE
If user update the banner picture or bio, system show the notification message hidden behind the menu options in the top navigation bar. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#46]
![Screenshot (1075)](https://user-images.githubusercontent.com/60692597/183395707-5a892fd7-a572-443b-9748-02deb6cf960b.png)

**Comment by BoPeng** [comment]
Moved down to avoid overlapping with the header..

![image](https://user-images.githubusercontent.com/9889312/183811020-830fb9c4-34af-468e-83bc-ff9cfbdfa2a4.png)

**Comment by Mashhood-Ehsan** [comment]
The issue is now checked/fixed, so closing it.
