### ISSUE TITLE
User Logged In > Dashboard > Edit icon is not working. When user click on the icon nothing happens. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#47]
![Screenshot (1076)](https://user-images.githubusercontent.com/60692597/183400296-90924b72-4f08-4ce3-9c7f-7a44d35b6fe6.png)

**Comment by BoPeng** [comment]
Cannot reproduce.

![image](https://user-images.githubusercontent.com/9889312/183811665-30416ea5-8d82-49ee-b298-da81f2975b65.png)

**Comment by Mashhood-Ehsan** [comment]
I have checked and it's working fine now, so closing this bug.
