### ISSUE TITLE
User logged-in > Forum > Ask a question > System gave server error 500 on submitting the question.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#48]
![Screenshot (1078)](https://user-images.githubusercontent.com/60692597/183449664-776c1843-072e-4cb4-bb4e-417e63ee915f.png)

**Comment by BoPeng** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/9889312/183812224-8a902dc1-8ebc-45ad-a4b3-1b691a101bca.png)

**Comment by Mashhood-Ehsan** [comment]
I have also tried again at my end, but was not able to reproduce it. 
So maybe there was a server glitch or something. 
So I'm closing this bug.
