### ISSUE TITLE
User logged in > Orders > Withdraw > If user entered a correct value in a field after a wrong value then system should remove the old message 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#50]
![Screenshot (1079)](https://user-images.githubusercontent.com/60692597/183455333-5f97d2d8-fbf2-42e4-a318-a14dc57f1240.png)

**Comment by BoPeng** [comment]
This can be done for this particular form, but in theory there could be multiple invalid fields so removing error messages could cause confusion.

**Comment by Mashhood-Ehsan** [comment]
As per the above comments, closing this issue.
