### ISSUE TITLE
User logged in > Orders > Add Credit > Purchase Giftcard functionality is not working. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#51]
The user has purchased a gift card for 25$. But that amount is not being deducted from the total balance of the user. 
Watch the below video:

https://share.vidyard.com/watch/TUw9sQukpM8sHzD6FrHDvB?

**Comment by bioworkflows** [comment]
I think this is because the credits are not by default used for payment, so the credit remains the same when the transaction is performed using credit card.

This will be addressed later.

**Comment by Mashhood-Ehsan** [comment]
So, as per the above comments, I am keeping it as open.

**Comment by bioworkflows** [comment]
The payment system has been improved. Please check.

**Comment by Mashhood-Ehsan** [comment]
The amount is still not being deducted from the user's balance.
As you can view in the videos, that user has purchased a 10$ gift card but the balance remains the same.

https://share.vidyard.com/watch/LzNLJiLLk6kF54QWtmedTy?

**Comment by bioworkflows** [comment]
Yes, a confirmation box somehow got blocked. Please try again.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it.

![Screenshot (1282)](https://user-images.githubusercontent.com/60692597/191911613-e349d879-f8a6-44ae-aa5a-17b38440f40a.png)
