### ISSUE TITLE
User logged-in > Forum > Ask a question > User is unable to add bounty to existing question. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#52]
When a user tries to add a bounty to an existing question, the system opens up a new question instead of opening an existing question.

https://share.vidyard.com/watch/hSg23H9ot2NKbAK3ASj6V7?

**Comment by BoPeng** [comment]
I am not sure what went wrong here. When user click "create a bounty", it goes to a form that creates a new bounty... I have updated the interface to make the form clearer.

**Comment by Mashhood-Ehsan** [comment]
Instead of clicking "create a bounty", what if the user wants to add a bounty to the existing question? 
Is it a valid scenario or not?

**Comment by Mashhood-Ehsan** [comment]
The user is not able to add a bounty to existing questions.
The system keeps displaying the 0$ amount by default.

![Screenshot (1277)](https://user-images.githubusercontent.com/60692597/191608007-beadb77b-e313-4548-acd0-65f0975b338d.png)

**Comment by bioworkflows** [comment]
Thanks. Again a wrongly-placed condition.

**Comment by Mashhood-Ehsan** [comment]
I'm still not sure, how to add bounty.
Can you please make a video

**Comment by Mashhood-Ehsan** [comment]
Was successfully able to post a bounty, so closing this defect. 

![Screenshot (1283)](https://user-images.githubusercontent.com/60692597/191914292-5d517cb9-6628-48c7-87c9-1dd58847b6d3.png)
