### ISSUE TITLE
User logged-In > Dashboard > Footer > Email/Message icon link is not working. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#53]
![4](https://user-images.githubusercontent.com/60692597/183464438-e6804099-22c2-42e3-a327-0f086544d30e.PNG)

**Comment by BoPeng** [comment]
Thanks. Changed the wrong `href`.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed/checked, so closing it now.
