### ISSUE TITLE
User logged in > Dashbaord > System should display 'unread notifications' instead of showing 'unread messages'

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#55]
![Screenshot (1082)](https://user-images.githubusercontent.com/60692597/183479721-e756ec33-e8dd-4b38-82e1-66f8cc51dddb.png)

**Comment by BoPeng** [comment]
Fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed/checked, so closing it now.
