### ISSUE TITLE
User logged In > dashboard > upload workflow > Title characters limit is 100 but still user can enter more characters than 100.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#56]
![5](https://user-images.githubusercontent.com/60692597/183721934-554208e3-e440-4cdd-8e07-24c9871c8d22.PNG)

**Comment by BoPeng** [comment]
The title of this ticket has 127 characters, so allowing longer titles might make sense.

I have updated the text to reflect the real underylying limit of 256 characters. I suspect that we need to trim the titles when the workflows are listed.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed/checked, so closing it now.
