### ISSUE TITLE
User logged in > dashboard > upload workflow > User has edited the workflow and saved it afterwards, but in actual these changes are not being reflected. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#61]
As you can see in the video, the user has edited and saved the description it. and then open the same workflow again but the changes are not saved. 

https://share.vidyard.com/watch/3pyCKBemcjBBbckc6c1Set?

**Comment by BoPeng** [comment]
This is caused by the extra long description (limited to 2000 characters for now), and the failure to display an error message. It has been fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed/checked, so closing it now.
