### ISSUE TITLE
User logged in > dashboard > upload workflow > User has written the description but still system is giving an error of 'A main description page is required'

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#62]
https://share.vidyard.com/watch/cnyAXk6MGdKa4kQoPtgk7R?

**Comment by BoPeng** [comment]
Main document refers to the mandatary upload, We have changed the error message to make it clearer.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed/checked, so closing it now.
