### ISSUE TITLE
User logged in > dashboard > upload workflow > service provided > Edit button is not working.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#63]
![8](https://user-images.githubusercontent.com/60692597/184008432-0394a88e-79a8-4376-8dac-8ce1720604a9.PNG)

**Comment by BoPeng** [comment]
Fixed in trunk.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed/checked, so closing it now.
