### ISSUE TITLE
User logged in > dashboard > upload workflow > service provided > Delete button is not working.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#64]
![9](https://user-images.githubusercontent.com/60692597/184008535-3da4ffc6-6e47-4851-b256-703206678db3.PNG)

**Comment by BoPeng** [comment]
Fixed. Note that this is a two step process. The first step is to "cancel" the support, and canceled support can be edited (and restored), or be permanently deleted. The 'canceled` support can be viewed by its author, but not by others.

**Comment by Mashhood-Ehsan** [comment]
I have checked the issue and now it's fixed.
