### ISSUE TITLE
Upload Workflow > Comments > Reply button is not working, when user click on the reply button nothing happens. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#65]
![Screenshot (1090)](https://user-images.githubusercontent.com/60692597/185290589-c73fe8a3-681b-4f8d-bf51-604ab678bd8a.png)

**Comment by bioworkflows** [comment]
Fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is getting resolved, so closing it 

![Screenshot (1266)](https://user-images.githubusercontent.com/60692597/191591011-b45a0037-de60-40b6-bbcf-4e004254e41d.png)
