### ISSUE TITLE
Upload workflow > Comments > If user edit a comment, system start displaying that comment as a seprate thread. Instead of overriding the existing comment. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#66]
![Screenshot (1091)](https://user-images.githubusercontent.com/60692597/185290750-733c20e3-8926-4fea-8829-6949101344cb.png)

**Comment by bioworkflows** [comment]
Cannot reproduce, maybe it has been fixed with #65

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it.

![Screenshot (1276)](https://user-images.githubusercontent.com/60692597/191607250-5f644985-9d4f-4732-9074-aa036f53a444.png)
