### ISSUE TITLE
Upload workflow > If the file name is too large then the 'delete' ico button alignment gets disturbed. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#67]
![Screenshot (1088)](https://user-images.githubusercontent.com/60692597/185290939-372ed0a5-ab2c-4623-b90f-6fc2c087ddda.png)

**Comment by bioworkflows** [comment]
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/47236991/189571750-5d45810a-7234-464c-ba9e-fe1f1dcd32ad.png">

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/47236991/189571832-00bb6b95-6f04-4897-a087-76f737eaaeff.png">

**Comment by Mashhood-Ehsan** [comment]
The issue is still not fixed. plz, check the attached screenshot.

![4](https://user-images.githubusercontent.com/60692597/191590207-5c3e7228-7596-41fa-b4a3-9ff33eaa88d2.PNG)

**Comment by bioworkflows** [comment]
During my testing the long filename is displayed in short form, but still "pushes" the file size out of the box. 

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/47236991/191651471-fdb65bf7-b424-4466-9bfc-1a80a3d4221b.png">

**Comment by bioworkflows** [comment]
Fixed using a combination of `width` and `max-width`.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it.

![Screenshot (1283)](https://user-images.githubusercontent.com/60692597/191912842-da966513-d648-4f07-b2d5-a03b3ed71b62.png)
