### ISSUE TITLE
If the request for withdrawl request get initiated, system should display a success message.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#68]
As you can also see in the current system, the system doesn't display anything when clicking on the 'Request Withdrawl' button.

**Comment by Mashhood-Ehsan** [comment]
https://share.vidyard.com/watch/mdErA6MUoh5Pzj2es8LLQS?

**Comment by BoPeng** [comment]
The request is not displayed while is being handled in the backend, but I agree that a "pending" withdraw item needs to be displayed.

**Comment by bioworkflows** [comment]
Fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed, so closing it.

![Screenshot (1278)](https://user-images.githubusercontent.com/60692597/191609707-3a41ceba-a33c-42a7-9d13-54e712992b1a.png)
