### ISSUE TITLE
There are big white space available on the homepage, where no text/images/labels are available. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#70]
![11](https://user-images.githubusercontent.com/60692597/186241300-bc31cb3a-d16f-47bb-b387-e5b8b4da738f.PNG)

**Comment by BoPeng** [comment]
Supposed on production there should be workflows to fill the space. e.g. https://bioworkflows.com/

**Comment by Mashhood-Ehsan** [comment]
As per the above comments, closing the issue.
