### ISSUE TITLE
Orders > Purchases > Account settings option is not working. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#71]
https://share.vidyard.com/watch/PVmB7CShB8d3FGbdwFouXG?

**Comment by bioworkflows** [comment]
Not sure what was fixed but this seems to be working again.

**Comment by Mashhood-Ehsan** [comment]
The issue is not occurring anymore, so closing it. 

![Screenshot (1265)](https://user-images.githubusercontent.com/60692597/191588809-6668d8f6-7b6b-46d5-8593-5c312e4ec2fe.png)
