### ISSUE TITLE
Cart > Orders > Add Credit > System is giving 500 server error, when user click on 'Pay Now' button. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#72]
![12](https://user-images.githubusercontent.com/60692597/186260008-d44f5797-4ff9-4bf1-bb02-6bfd47590902.PNG)

**Comment by bioworkflows** [comment]
This has been rewritten.

**Comment by Mashhood-Ehsan** [comment]
Not facing this issue anymore, so closing it.
