### ISSUE TITLE
Forum > Messages > If there are no recent messages available then system must display a message like i.e. "No recent messages" instead of showing blank white spaces. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#73]
![13](https://user-images.githubusercontent.com/60692597/186261266-d26b2ff5-57c4-4be4-9cf0-c6dfbe860a60.PNG)

**Comment by bioworkflows** [comment]
Fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![5](https://user-images.githubusercontent.com/60692597/191590642-9cf2d697-f90b-4c7f-99e6-35b8dd84090c.PNG)
