### ISSUE TITLE
Style the email confirmation page

### ISSUE THREAD

**Issue by BoPeng** [bioworkflows/bioworkflows-help#76]
<img width="2438" alt="image" src="https://user-images.githubusercontent.com/9889312/186512808-9927609a-23db-4d3f-9c9e-d47913b1c172.png">

**Comment by bioworkflows** [comment]
This is related to another sign on issue, caused by the update of a third-party module. It should have been fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue has been fixed, so closing it.

![image](https://user-images.githubusercontent.com/60692597/191613102-33d2ca80-3a97-4e0e-a440-6a679b36e0e9.png)
