### ISSUE TITLE
Add workflow to cart > Checkout > 'Extended license' toggle option is not working.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#77]
The toggle button is turning on/off by itself.

https://share.vidyard.com/watch/y1oqsnbXp7pRb4qwwLd64J?

**Comment by bioworkflows** [comment]
Should be working now.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed, so closing it.

![8](https://user-images.githubusercontent.com/60692597/191603396-97afb21c-5443-468f-b179-b8acfcf73ca0.PNG)
