### ISSUE TITLE
Shopping Cart > System is displaying the dollar sign two times ($$) along with the price. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#79]
![Screenshot (1132) - Copy](https://user-images.githubusercontent.com/60692597/186882560-692a3bfd-a7df-4699-906a-02fffd88663b.png)

**Comment by bioworkflows** [comment]
Fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![Screenshot (1264)](https://user-images.githubusercontent.com/60692597/191587537-2b37a6eb-3042-4b9f-b366-b7e1ec61376d.png)
