### ISSUE TITLE
Purchase workflow > Proceeds to Checkout > If user is already on 'Checkout' page, then system should not display the 'checkout' button inside the card.  

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#81]
![Screenshot (1133)](https://user-images.githubusercontent.com/60692597/186884084-5e3fd34e-5c86-405e-a3ac-d1c910b94305.png)

**Comment by bioworkflows** [comment]
This is difficult to fix since the two are separate pieces and do not know the existence of each other.

**Comment by Mashhood-Ehsan** [comment]
After discussion, closing the issue.
