### ISSUE TITLE
Rate Workflow > The ratting card is not displaying the ratting stars. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#82]
![16](https://user-images.githubusercontent.com/60692597/186885260-4792d0f7-6bc7-4e98-b7e9-064dab44f6f5.PNG)

**Comment by bioworkflows** [comment]
Seems to be working now.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it.

![Screenshot (1271)](https://user-images.githubusercontent.com/60692597/191599754-c9d505c1-af66-4bd6-a8e6-dd629e760630.png)
