### ISSUE TITLE
Workflow Rate > When user click on 'submit for approval' button, without entering data inside the comment section. Then system start dispalying the two 'comments' text areas. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#83]
https://share.vidyard.com/watch/VMH1Fs9ji7J67FpvRmW2TE?

**Comment by bioworkflows** [comment]
Should be fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed, so closing it.

![Screenshot (1272)](https://user-images.githubusercontent.com/60692597/191601591-2976e814-c6ae-46e2-acb2-e82d556f4d01.png)
