### ISSUE TITLE
Workflow Rate > System is displaying 'This field is required' error two times.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#84]
https://share.vidyard.com/watch/VMH1Fs9ji7J67FpvRmW2TE?

**Comment by bioworkflows** [comment]
Should have been fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![Screenshot (1272)](https://user-images.githubusercontent.com/60692597/191600089-cf9dafc6-e5d1-49c8-b122-971995aaf6bd.png)
