### ISSUE TITLE
Workflow > Heart react button is not working.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#85]
The user has purchased the workflow. But he/she is unable to heart react to it. 

![18](https://user-images.githubusercontent.com/60692597/186900335-21cdaacc-a680-4a06-8cb8-67dc50ac88f1.PNG)

**Comment by bioworkflows** [comment]
This is actually the bookmark count. It has been replaced with the bookmark icon and related bookmark/unbookmark action.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![Screenshot (1263)](https://user-images.githubusercontent.com/60692597/191586643-480faad7-a46e-4e57-9ba3-85647eb62b85.png)
