### ISSUE TITLE
Workflow > Reviews > System is displaying the user's reviews with <P> tag.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#86]
![17](https://user-images.githubusercontent.com/60692597/186900454-068f4a75-07aa-40c2-a70e-9b5828d42643.PNG)

**Comment by bioworkflows** [comment]
Fixed.

**Comment by Mashhood-Ehsan** [comment]
The user is not able to post any reviews. 
The review section seems disabled. 

![3](https://user-images.githubusercontent.com/60692597/191586207-f5caa419-2b6b-48d3-bd7f-fbd8319d305a.PNG)

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed, so closing it.

![Screenshot (1273)](https://user-images.githubusercontent.com/60692597/191601273-d0dbe3e4-4200-45cc-abc1-6d027ec4a60f.png)
