### ISSUE TITLE
Request a refund > When 'Request a refund' card opens up scroll up/down stop working. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#88]
Users become unable to scroll up/down even with a mouse click and also with the mouse scroll button. 

https://share.vidyard.com/watch/hobLx8FhS51eoQH1PfAZr5?

**Comment by bioworkflows** [comment]
The modal dialog is unnecessarily large so we have made it more compact

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/47236991/189536617-a34b435f-52cc-4f05-aa93-f3ce2709564b.png">

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it.

![Screenshot (1274)](https://user-images.githubusercontent.com/60692597/191601462-be8f58c4-6ffb-4495-af54-3a442a34aeb4.png)
