### ISSUE TITLE
All Workflows > Search > When user filter the workflows by 'Free Workflows' filter, system is dispalying the free workflows along with the paid workflows. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#90]
![Screenshot (1134)](https://user-images.githubusercontent.com/60692597/186919340-639a607c-0e35-4468-94f6-5cdcf65e621b.png)

**Comment by bioworkflows** [comment]
The dropdown was mixed up with the "price" selection from the advanced search. I have removed it altogether.

**Comment by Mashhood-Ehsan** [comment]
This issue is now resolved, so closing it. 

![2](https://user-images.githubusercontent.com/60692597/191578351-a67138e5-b8af-4103-860c-c864e55425e0.PNG)
