### ISSUE TITLE
Questions > Bookmark a question > User is unable to view the bookmarked questions.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#91]
The user has bookmarked a question. But he/she is unable to view where this question is being saved. 

![Screenshot (1135)](https://user-images.githubusercontent.com/60692597/186922592-91bdb551-e46d-40d1-b8bb-1a7030396dbc.png)

**Comment by BoPeng** [comment]
However, maybe this is an overkill, we added a dropdown to show all bookmarked topics.

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/9889312/189536352-cb112fd6-b717-4e30-ac7f-70e9b42b19fd.png">

**Comment by bioworkflows** [comment]
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/47236991/189543731-529d3c46-4646-4e05-a63f-724026a69c23.png">

Simplified the interface.

**Comment by Mashhood-Ehsan** [comment]
The user is unable to bookmark the question.
The option is disabled and the user cannot click on it. 

![1](https://user-images.githubusercontent.com/60692597/191575224-edb7b638-0252-43fa-ba4c-94490e6b2d21.PNG)

**Comment by BoPeng** [comment]
Because this is user's own workflow, so he is not supposed to bookmark it. At least this is how it is implemented now.

**Comment by Mashhood-Ehsan** [comment]
This is the question, which is posted by another user.

**Comment by BoPeng** [comment]
A reversed condition was set. Fixed.

**Comment by Mashhood-Ehsan** [comment]
The issue is now fixed, so closing it.

![Screenshot (1285)](https://user-images.githubusercontent.com/60692597/191914142-2153e13a-5c14-4b63-b44f-d75d94a2c4ee.png)
