### ISSUE TITLE
Style of menu header

### ISSUE THREAD

**Issue by BoPeng** [bioworkflows/bioworkflows-help#92]
We could mimic the following style for header menu

![image](https://user-images.githubusercontent.com/9889312/186941677-819320c3-fdee-4411-8181-73650fa25066.png)

**Comment by bioworkflows** [comment]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/47236991/187321196-c6d1913e-e2b8-415b-99d7-22139e165c83.png">
